// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fps.proto

package filecoin_ffs_pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddCidRequest struct {
	Cid                  string   `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddCidRequest) Reset()         { *m = AddCidRequest{} }
func (m *AddCidRequest) String() string { return proto.CompactTextString(m) }
func (*AddCidRequest) ProtoMessage()    {}
func (*AddCidRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_23fdef2ae1f06360, []int{0}
}

func (m *AddCidRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCidRequest.Unmarshal(m, b)
}
func (m *AddCidRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCidRequest.Marshal(b, m, deterministic)
}
func (m *AddCidRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCidRequest.Merge(m, src)
}
func (m *AddCidRequest) XXX_Size() int {
	return xxx_messageInfo_AddCidRequest.Size(m)
}
func (m *AddCidRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCidRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddCidRequest proto.InternalMessageInfo

func (m *AddCidRequest) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

type AddCidReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddCidReply) Reset()         { *m = AddCidReply{} }
func (m *AddCidReply) String() string { return proto.CompactTextString(m) }
func (*AddCidReply) ProtoMessage()    {}
func (*AddCidReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_23fdef2ae1f06360, []int{1}
}

func (m *AddCidReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCidReply.Unmarshal(m, b)
}
func (m *AddCidReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCidReply.Marshal(b, m, deterministic)
}
func (m *AddCidReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCidReply.Merge(m, src)
}
func (m *AddCidReply) XXX_Size() int {
	return xxx_messageInfo_AddCidReply.Size(m)
}
func (m *AddCidReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCidReply.DiscardUnknown(m)
}

var xxx_messageInfo_AddCidReply proto.InternalMessageInfo

type AddFileRequest struct {
	Chunk                []byte   `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddFileRequest) Reset()         { *m = AddFileRequest{} }
func (m *AddFileRequest) String() string { return proto.CompactTextString(m) }
func (*AddFileRequest) ProtoMessage()    {}
func (*AddFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_23fdef2ae1f06360, []int{2}
}

func (m *AddFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddFileRequest.Unmarshal(m, b)
}
func (m *AddFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddFileRequest.Marshal(b, m, deterministic)
}
func (m *AddFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddFileRequest.Merge(m, src)
}
func (m *AddFileRequest) XXX_Size() int {
	return xxx_messageInfo_AddFileRequest.Size(m)
}
func (m *AddFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddFileRequest proto.InternalMessageInfo

func (m *AddFileRequest) GetChunk() []byte {
	if m != nil {
		return m.Chunk
	}
	return nil
}

type AddFileReply struct {
	Cid                  string   `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddFileReply) Reset()         { *m = AddFileReply{} }
func (m *AddFileReply) String() string { return proto.CompactTextString(m) }
func (*AddFileReply) ProtoMessage()    {}
func (*AddFileReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_23fdef2ae1f06360, []int{3}
}

func (m *AddFileReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddFileReply.Unmarshal(m, b)
}
func (m *AddFileReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddFileReply.Marshal(b, m, deterministic)
}
func (m *AddFileReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddFileReply.Merge(m, src)
}
func (m *AddFileReply) XXX_Size() int {
	return xxx_messageInfo_AddFileReply.Size(m)
}
func (m *AddFileReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AddFileReply.DiscardUnknown(m)
}

var xxx_messageInfo_AddFileReply proto.InternalMessageInfo

func (m *AddFileReply) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

type GetRequest struct {
	Cid                  string   `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_23fdef2ae1f06360, []int{4}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

type GetReply struct {
	Chunk                []byte   `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReply) Reset()         { *m = GetReply{} }
func (m *GetReply) String() string { return proto.CompactTextString(m) }
func (*GetReply) ProtoMessage()    {}
func (*GetReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_23fdef2ae1f06360, []int{5}
}

func (m *GetReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReply.Unmarshal(m, b)
}
func (m *GetReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReply.Marshal(b, m, deterministic)
}
func (m *GetReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReply.Merge(m, src)
}
func (m *GetReply) XXX_Size() int {
	return xxx_messageInfo_GetReply.Size(m)
}
func (m *GetReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetReply proto.InternalMessageInfo

func (m *GetReply) GetChunk() []byte {
	if m != nil {
		return m.Chunk
	}
	return nil
}

type CreateRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_23fdef2ae1f06360, []int{6}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

type CreateReply struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateReply) Reset()         { *m = CreateReply{} }
func (m *CreateReply) String() string { return proto.CompactTextString(m) }
func (*CreateReply) ProtoMessage()    {}
func (*CreateReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_23fdef2ae1f06360, []int{7}
}

func (m *CreateReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReply.Unmarshal(m, b)
}
func (m *CreateReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReply.Marshal(b, m, deterministic)
}
func (m *CreateReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReply.Merge(m, src)
}
func (m *CreateReply) XXX_Size() int {
	return xxx_messageInfo_CreateReply.Size(m)
}
func (m *CreateReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReply proto.InternalMessageInfo

func (m *CreateReply) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateReply) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type ShowRequest struct {
	Cid                  string   `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShowRequest) Reset()         { *m = ShowRequest{} }
func (m *ShowRequest) String() string { return proto.CompactTextString(m) }
func (*ShowRequest) ProtoMessage()    {}
func (*ShowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_23fdef2ae1f06360, []int{8}
}

func (m *ShowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowRequest.Unmarshal(m, b)
}
func (m *ShowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowRequest.Marshal(b, m, deterministic)
}
func (m *ShowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowRequest.Merge(m, src)
}
func (m *ShowRequest) XXX_Size() int {
	return xxx_messageInfo_ShowRequest.Size(m)
}
func (m *ShowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShowRequest proto.InternalMessageInfo

func (m *ShowRequest) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

type InfoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfoRequest) Reset()         { *m = InfoRequest{} }
func (m *InfoRequest) String() string { return proto.CompactTextString(m) }
func (*InfoRequest) ProtoMessage()    {}
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_23fdef2ae1f06360, []int{9}
}

func (m *InfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoRequest.Unmarshal(m, b)
}
func (m *InfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoRequest.Marshal(b, m, deterministic)
}
func (m *InfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoRequest.Merge(m, src)
}
func (m *InfoRequest) XXX_Size() int {
	return xxx_messageInfo_InfoRequest.Size(m)
}
func (m *InfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InfoRequest proto.InternalMessageInfo

type InfoReply struct {
	Id                   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Wallet               *WalletInfo `protobuf:"bytes,2,opt,name=wallet,proto3" json:"wallet,omitempty"`
	Pins                 []string    `protobuf:"bytes,3,rep,name=pins,proto3" json:"pins,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *InfoReply) Reset()         { *m = InfoReply{} }
func (m *InfoReply) String() string { return proto.CompactTextString(m) }
func (*InfoReply) ProtoMessage()    {}
func (*InfoReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_23fdef2ae1f06360, []int{10}
}

func (m *InfoReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoReply.Unmarshal(m, b)
}
func (m *InfoReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoReply.Marshal(b, m, deterministic)
}
func (m *InfoReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoReply.Merge(m, src)
}
func (m *InfoReply) XXX_Size() int {
	return xxx_messageInfo_InfoReply.Size(m)
}
func (m *InfoReply) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoReply.DiscardUnknown(m)
}

var xxx_messageInfo_InfoReply proto.InternalMessageInfo

func (m *InfoReply) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *InfoReply) GetWallet() *WalletInfo {
	if m != nil {
		return m.Wallet
	}
	return nil
}

func (m *InfoReply) GetPins() []string {
	if m != nil {
		return m.Pins
	}
	return nil
}

type WalletInfo struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Balance              uint64   `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WalletInfo) Reset()         { *m = WalletInfo{} }
func (m *WalletInfo) String() string { return proto.CompactTextString(m) }
func (*WalletInfo) ProtoMessage()    {}
func (*WalletInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_23fdef2ae1f06360, []int{11}
}

func (m *WalletInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WalletInfo.Unmarshal(m, b)
}
func (m *WalletInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WalletInfo.Marshal(b, m, deterministic)
}
func (m *WalletInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WalletInfo.Merge(m, src)
}
func (m *WalletInfo) XXX_Size() int {
	return xxx_messageInfo_WalletInfo.Size(m)
}
func (m *WalletInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_WalletInfo.DiscardUnknown(m)
}

var xxx_messageInfo_WalletInfo proto.InternalMessageInfo

func (m *WalletInfo) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *WalletInfo) GetBalance() uint64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

type ShowReply struct {
	Cid                  string              `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Created              int64               `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	Hot                  *ShowReply_HotInfo  `protobuf:"bytes,3,opt,name=hot,proto3" json:"hot,omitempty"`
	Cold                 *ShowReply_ColdInfo `protobuf:"bytes,4,opt,name=cold,proto3" json:"cold,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ShowReply) Reset()         { *m = ShowReply{} }
func (m *ShowReply) String() string { return proto.CompactTextString(m) }
func (*ShowReply) ProtoMessage()    {}
func (*ShowReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_23fdef2ae1f06360, []int{12}
}

func (m *ShowReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowReply.Unmarshal(m, b)
}
func (m *ShowReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowReply.Marshal(b, m, deterministic)
}
func (m *ShowReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowReply.Merge(m, src)
}
func (m *ShowReply) XXX_Size() int {
	return xxx_messageInfo_ShowReply.Size(m)
}
func (m *ShowReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowReply.DiscardUnknown(m)
}

var xxx_messageInfo_ShowReply proto.InternalMessageInfo

func (m *ShowReply) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

func (m *ShowReply) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *ShowReply) GetHot() *ShowReply_HotInfo {
	if m != nil {
		return m.Hot
	}
	return nil
}

func (m *ShowReply) GetCold() *ShowReply_ColdInfo {
	if m != nil {
		return m.Cold
	}
	return nil
}

type ShowReply_HotInfo struct {
	Size                 int64                  `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	Ipfs                 *ShowReply_IpfsHotInfo `protobuf:"bytes,2,opt,name=ipfs,proto3" json:"ipfs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ShowReply_HotInfo) Reset()         { *m = ShowReply_HotInfo{} }
func (m *ShowReply_HotInfo) String() string { return proto.CompactTextString(m) }
func (*ShowReply_HotInfo) ProtoMessage()    {}
func (*ShowReply_HotInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_23fdef2ae1f06360, []int{12, 0}
}

func (m *ShowReply_HotInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowReply_HotInfo.Unmarshal(m, b)
}
func (m *ShowReply_HotInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowReply_HotInfo.Marshal(b, m, deterministic)
}
func (m *ShowReply_HotInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowReply_HotInfo.Merge(m, src)
}
func (m *ShowReply_HotInfo) XXX_Size() int {
	return xxx_messageInfo_ShowReply_HotInfo.Size(m)
}
func (m *ShowReply_HotInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowReply_HotInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ShowReply_HotInfo proto.InternalMessageInfo

func (m *ShowReply_HotInfo) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ShowReply_HotInfo) GetIpfs() *ShowReply_IpfsHotInfo {
	if m != nil {
		return m.Ipfs
	}
	return nil
}

type ShowReply_IpfsHotInfo struct {
	Created              int64    `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShowReply_IpfsHotInfo) Reset()         { *m = ShowReply_IpfsHotInfo{} }
func (m *ShowReply_IpfsHotInfo) String() string { return proto.CompactTextString(m) }
func (*ShowReply_IpfsHotInfo) ProtoMessage()    {}
func (*ShowReply_IpfsHotInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_23fdef2ae1f06360, []int{12, 1}
}

func (m *ShowReply_IpfsHotInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowReply_IpfsHotInfo.Unmarshal(m, b)
}
func (m *ShowReply_IpfsHotInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowReply_IpfsHotInfo.Marshal(b, m, deterministic)
}
func (m *ShowReply_IpfsHotInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowReply_IpfsHotInfo.Merge(m, src)
}
func (m *ShowReply_IpfsHotInfo) XXX_Size() int {
	return xxx_messageInfo_ShowReply_IpfsHotInfo.Size(m)
}
func (m *ShowReply_IpfsHotInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowReply_IpfsHotInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ShowReply_IpfsHotInfo proto.InternalMessageInfo

func (m *ShowReply_IpfsHotInfo) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

type ShowReply_ColdInfo struct {
	Filecoin             *ShowReply_FilInfo `protobuf:"bytes,1,opt,name=filecoin,proto3" json:"filecoin,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ShowReply_ColdInfo) Reset()         { *m = ShowReply_ColdInfo{} }
func (m *ShowReply_ColdInfo) String() string { return proto.CompactTextString(m) }
func (*ShowReply_ColdInfo) ProtoMessage()    {}
func (*ShowReply_ColdInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_23fdef2ae1f06360, []int{12, 2}
}

func (m *ShowReply_ColdInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowReply_ColdInfo.Unmarshal(m, b)
}
func (m *ShowReply_ColdInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowReply_ColdInfo.Marshal(b, m, deterministic)
}
func (m *ShowReply_ColdInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowReply_ColdInfo.Merge(m, src)
}
func (m *ShowReply_ColdInfo) XXX_Size() int {
	return xxx_messageInfo_ShowReply_ColdInfo.Size(m)
}
func (m *ShowReply_ColdInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowReply_ColdInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ShowReply_ColdInfo proto.InternalMessageInfo

func (m *ShowReply_ColdInfo) GetFilecoin() *ShowReply_FilInfo {
	if m != nil {
		return m.Filecoin
	}
	return nil
}

type ShowReply_FilInfo struct {
	DataCid              string                  `protobuf:"bytes,1,opt,name=dataCid,proto3" json:"dataCid,omitempty"`
	Proposals            []*ShowReply_FilStorage `protobuf:"bytes,2,rep,name=proposals,proto3" json:"proposals,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ShowReply_FilInfo) Reset()         { *m = ShowReply_FilInfo{} }
func (m *ShowReply_FilInfo) String() string { return proto.CompactTextString(m) }
func (*ShowReply_FilInfo) ProtoMessage()    {}
func (*ShowReply_FilInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_23fdef2ae1f06360, []int{12, 3}
}

func (m *ShowReply_FilInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowReply_FilInfo.Unmarshal(m, b)
}
func (m *ShowReply_FilInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowReply_FilInfo.Marshal(b, m, deterministic)
}
func (m *ShowReply_FilInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowReply_FilInfo.Merge(m, src)
}
func (m *ShowReply_FilInfo) XXX_Size() int {
	return xxx_messageInfo_ShowReply_FilInfo.Size(m)
}
func (m *ShowReply_FilInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowReply_FilInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ShowReply_FilInfo proto.InternalMessageInfo

func (m *ShowReply_FilInfo) GetDataCid() string {
	if m != nil {
		return m.DataCid
	}
	return ""
}

func (m *ShowReply_FilInfo) GetProposals() []*ShowReply_FilStorage {
	if m != nil {
		return m.Proposals
	}
	return nil
}

type ShowReply_FilStorage struct {
	ProposalCid          string   `protobuf:"bytes,1,opt,name=proposalCid,proto3" json:"proposalCid,omitempty"`
	Duration             int64    `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
	ActivationEpoch      int64    `protobuf:"varint,3,opt,name=activationEpoch,proto3" json:"activationEpoch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShowReply_FilStorage) Reset()         { *m = ShowReply_FilStorage{} }
func (m *ShowReply_FilStorage) String() string { return proto.CompactTextString(m) }
func (*ShowReply_FilStorage) ProtoMessage()    {}
func (*ShowReply_FilStorage) Descriptor() ([]byte, []int) {
	return fileDescriptor_23fdef2ae1f06360, []int{12, 4}
}

func (m *ShowReply_FilStorage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowReply_FilStorage.Unmarshal(m, b)
}
func (m *ShowReply_FilStorage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowReply_FilStorage.Marshal(b, m, deterministic)
}
func (m *ShowReply_FilStorage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowReply_FilStorage.Merge(m, src)
}
func (m *ShowReply_FilStorage) XXX_Size() int {
	return xxx_messageInfo_ShowReply_FilStorage.Size(m)
}
func (m *ShowReply_FilStorage) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowReply_FilStorage.DiscardUnknown(m)
}

var xxx_messageInfo_ShowReply_FilStorage proto.InternalMessageInfo

func (m *ShowReply_FilStorage) GetProposalCid() string {
	if m != nil {
		return m.ProposalCid
	}
	return ""
}

func (m *ShowReply_FilStorage) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *ShowReply_FilStorage) GetActivationEpoch() int64 {
	if m != nil {
		return m.ActivationEpoch
	}
	return 0
}

func init() {
	proto.RegisterType((*AddCidRequest)(nil), "filecoin.ffs.pb.AddCidRequest")
	proto.RegisterType((*AddCidReply)(nil), "filecoin.ffs.pb.AddCidReply")
	proto.RegisterType((*AddFileRequest)(nil), "filecoin.ffs.pb.AddFileRequest")
	proto.RegisterType((*AddFileReply)(nil), "filecoin.ffs.pb.AddFileReply")
	proto.RegisterType((*GetRequest)(nil), "filecoin.ffs.pb.GetRequest")
	proto.RegisterType((*GetReply)(nil), "filecoin.ffs.pb.GetReply")
	proto.RegisterType((*CreateRequest)(nil), "filecoin.ffs.pb.CreateRequest")
	proto.RegisterType((*CreateReply)(nil), "filecoin.ffs.pb.CreateReply")
	proto.RegisterType((*ShowRequest)(nil), "filecoin.ffs.pb.ShowRequest")
	proto.RegisterType((*InfoRequest)(nil), "filecoin.ffs.pb.InfoRequest")
	proto.RegisterType((*InfoReply)(nil), "filecoin.ffs.pb.InfoReply")
	proto.RegisterType((*WalletInfo)(nil), "filecoin.ffs.pb.WalletInfo")
	proto.RegisterType((*ShowReply)(nil), "filecoin.ffs.pb.ShowReply")
	proto.RegisterType((*ShowReply_HotInfo)(nil), "filecoin.ffs.pb.ShowReply.HotInfo")
	proto.RegisterType((*ShowReply_IpfsHotInfo)(nil), "filecoin.ffs.pb.ShowReply.IpfsHotInfo")
	proto.RegisterType((*ShowReply_ColdInfo)(nil), "filecoin.ffs.pb.ShowReply.ColdInfo")
	proto.RegisterType((*ShowReply_FilInfo)(nil), "filecoin.ffs.pb.ShowReply.FilInfo")
	proto.RegisterType((*ShowReply_FilStorage)(nil), "filecoin.ffs.pb.ShowReply.FilStorage")
}

func init() {
	proto.RegisterFile("fps.proto", fileDescriptor_23fdef2ae1f06360)
}

var fileDescriptor_23fdef2ae1f06360 = []byte{
	// 631 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x55, 0xdd, 0x6e, 0xd3, 0x4c,
	0x10, 0xad, 0xb3, 0xfe, 0x9a, 0x64, 0xdc, 0x9f, 0x4f, 0x2b, 0x2e, 0x82, 0x81, 0x36, 0x18, 0x51,
	0x72, 0x65, 0x41, 0x8b, 0x54, 0x89, 0x0b, 0x44, 0x1a, 0xf5, 0x0f, 0x09, 0xa9, 0x72, 0x2b, 0x21,
	0x2e, 0x5d, 0xef, 0x9a, 0xac, 0x58, 0x65, 0x4d, 0xbc, 0xa5, 0x94, 0xc7, 0xe1, 0x15, 0x78, 0x17,
	0x9e, 0x07, 0xed, 0xd8, 0xeb, 0x38, 0x89, 0x93, 0x3b, 0xcf, 0xcf, 0x39, 0x67, 0x66, 0xb2, 0x3d,
	0x85, 0x6e, 0x9a, 0xe5, 0x61, 0x36, 0x55, 0x5a, 0xd1, 0xdd, 0x54, 0x48, 0x9e, 0x28, 0x31, 0x09,
	0xd3, 0x34, 0x0f, 0xb3, 0xdb, 0xe0, 0x39, 0x6c, 0x0f, 0x19, 0x1b, 0x09, 0x16, 0xf1, 0xef, 0x77,
	0x3c, 0xd7, 0xf4, 0x7f, 0x20, 0x89, 0x60, 0x3d, 0xa7, 0xef, 0x0c, 0xba, 0x91, 0xf9, 0x0c, 0xb6,
	0xc1, 0xb3, 0x2d, 0x99, 0x7c, 0x08, 0x0e, 0x60, 0x67, 0xc8, 0xd8, 0x99, 0x90, 0xdc, 0x42, 0x1e,
	0xc1, 0x7f, 0xc9, 0xf8, 0x6e, 0xf2, 0x0d, 0x41, 0x5b, 0x51, 0x11, 0x04, 0x7d, 0xd8, 0xaa, 0xfa,
	0x32, 0xf9, 0xd0, 0x40, 0xbc, 0x07, 0x70, 0xce, 0xf5, 0x6a, 0xe1, 0x3e, 0x74, 0xb0, 0x6e, 0xd0,
	0xcd, 0x1a, 0xbb, 0xb0, 0x3d, 0x9a, 0xf2, 0x58, 0xdb, 0x51, 0x82, 0x63, 0xf0, 0x6c, 0xc2, 0xa0,
	0x76, 0xa0, 0x55, 0x51, 0xb6, 0x04, 0xa3, 0x3d, 0x68, 0xc7, 0x8c, 0x4d, 0x79, 0x9e, 0xf7, 0x5a,
	0x98, 0xb4, 0x61, 0xb0, 0x0f, 0xde, 0xf5, 0x58, 0xdd, 0xaf, 0xbd, 0xc2, 0xe5, 0x24, 0x55, 0x56,
	0x88, 0x41, 0xb7, 0x08, 0x9b, 0x64, 0x8e, 0x60, 0xf3, 0x3e, 0x96, 0x92, 0x6b, 0x54, 0xf1, 0x0e,
	0x9f, 0x84, 0x0b, 0x67, 0x0f, 0x3f, 0x63, 0x19, 0x19, 0xca, 0x56, 0x4a, 0xc1, 0xcd, 0xc4, 0x24,
	0xef, 0x91, 0x3e, 0x19, 0x74, 0x23, 0xfc, 0x0e, 0x3e, 0x00, 0xcc, 0x3a, 0xeb, 0xd3, 0x3b, 0x73,
	0xd3, 0x9b, 0xca, 0x6d, 0x2c, 0xe3, 0x49, 0xc2, 0x51, 0xd1, 0x8d, 0x6c, 0x18, 0xfc, 0x75, 0xa1,
	0x5b, 0x2c, 0xd6, 0xf8, 0x1b, 0x18, 0x64, 0x82, 0x07, 0x63, 0x88, 0x24, 0x91, 0x0d, 0xe9, 0x5b,
	0x20, 0x63, 0xa5, 0x7b, 0x04, 0x37, 0x08, 0x96, 0x36, 0xa8, 0x48, 0xc3, 0x0b, 0x55, 0x2c, 0x62,
	0xda, 0xe9, 0x31, 0xb8, 0x89, 0x92, 0xac, 0xe7, 0x22, 0xec, 0xc5, 0x1a, 0xd8, 0x48, 0x49, 0x86,
	0x38, 0x04, 0xf8, 0x5f, 0xa0, 0x5d, 0x12, 0x99, 0x4b, 0xe4, 0xe2, 0x17, 0xc7, 0x31, 0x49, 0x84,
	0xdf, 0xf4, 0x1d, 0xb8, 0x22, 0x4b, 0xf3, 0xf2, 0xa0, 0x07, 0x6b, 0x78, 0x2f, 0xb3, 0x34, 0xb7,
	0x23, 0x21, 0xc6, 0x7f, 0x05, 0x5e, 0x2d, 0x59, 0x5f, 0xd9, 0x99, 0x5b, 0xd9, 0xff, 0x08, 0x1d,
	0x3b, 0x15, 0x7d, 0x0f, 0x1d, 0xab, 0x81, 0x6d, 0xeb, 0x6f, 0x70, 0x26, 0x24, 0x0a, 0x56, 0x18,
	0x7f, 0x0c, 0xed, 0x32, 0x69, 0x04, 0x59, 0xac, 0xe3, 0x51, 0x75, 0x79, 0x1b, 0xd2, 0x11, 0x74,
	0xb3, 0xa9, 0xca, 0x54, 0x1e, 0x4b, 0xb3, 0x1a, 0x19, 0x78, 0x87, 0x2f, 0xd7, 0xab, 0x5c, 0x6b,
	0x35, 0x8d, 0xbf, 0xf2, 0x68, 0x86, 0xf3, 0x35, 0xc0, 0xac, 0x40, 0xfb, 0xe0, 0xd9, 0xd2, 0x4c,
	0xb0, 0x9e, 0xa2, 0x3e, 0x74, 0xd8, 0xdd, 0x34, 0xd6, 0x42, 0x4d, 0xca, 0xdf, 0xbc, 0x8a, 0xe9,
	0x00, 0x76, 0xe3, 0x44, 0x8b, 0x1f, 0x18, 0x9d, 0x66, 0x2a, 0x19, 0xe3, 0x03, 0x20, 0xd1, 0x62,
	0xfa, 0xf0, 0x0f, 0x01, 0x32, 0xbc, 0xba, 0xa4, 0x17, 0xb0, 0x59, 0xb8, 0x03, 0xdd, 0x5b, 0x9a,
	0x7c, 0xce, 0x59, 0xfc, 0xa7, 0x2b, 0xeb, 0xc6, 0x56, 0x36, 0xe8, 0x27, 0x68, 0x97, 0x86, 0x41,
	0xf7, 0x9b, 0x5a, 0x6b, 0x96, 0xe3, 0x3f, 0x5b, 0xdd, 0x80, 0x64, 0x03, 0x87, 0x0e, 0x81, 0x9c,
	0x73, 0x4d, 0x97, 0xff, 0xf6, 0x66, 0x9e, 0xe3, 0x3f, 0x6e, 0x2e, 0x22, 0xc5, 0x6b, 0xc7, 0xec,
	0x56, 0xb8, 0x49, 0xc3, 0x6e, 0x73, 0xbe, 0xd3, 0xb0, 0x5b, 0xcd, 0x86, 0x82, 0x0d, 0x7a, 0x02,
	0x2e, 0x3e, 0x85, 0xe5, 0xbe, 0x9a, 0xa9, 0xf8, 0xfe, 0x8a, 0x6a, 0xc5, 0x61, 0x9e, 0x42, 0x03,
	0x47, 0xcd, 0xb9, 0x1a, 0x38, 0xaa, 0xf7, 0x13, 0x6c, 0x9c, 0xbc, 0x01, 0x5f, 0xa8, 0x50, 0xf3,
	0x9f, 0x5a, 0x48, 0xbe, 0xd8, 0x79, 0xe2, 0x9d, 0x95, 0x89, 0x34, 0xcd, 0xaf, 0x9c, 0xdf, 0x2d,
	0x72, 0x73, 0x73, 0x7a, 0xbb, 0x89, 0xff, 0x39, 0x8e, 0xfe, 0x05, 0x00, 0x00, 0xff, 0xff, 0xe7,
	0x16, 0x23, 0x1b, 0x46, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// APIClient is the client API for API service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type APIClient interface {
	AddCid(ctx context.Context, in *AddCidRequest, opts ...grpc.CallOption) (*AddCidReply, error)
	AddFile(ctx context.Context, opts ...grpc.CallOption) (API_AddFileClient, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (API_GetClient, error)
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateReply, error)
	Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoReply, error)
	Show(ctx context.Context, in *ShowRequest, opts ...grpc.CallOption) (*ShowReply, error)
}

type aPIClient struct {
	cc grpc.ClientConnInterface
}

func NewAPIClient(cc grpc.ClientConnInterface) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) AddCid(ctx context.Context, in *AddCidRequest, opts ...grpc.CallOption) (*AddCidReply, error) {
	out := new(AddCidReply)
	err := c.cc.Invoke(ctx, "/filecoin.ffs.pb.API/AddCid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) AddFile(ctx context.Context, opts ...grpc.CallOption) (API_AddFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &_API_serviceDesc.Streams[0], "/filecoin.ffs.pb.API/AddFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &aPIAddFileClient{stream}
	return x, nil
}

type API_AddFileClient interface {
	Send(*AddFileRequest) error
	CloseAndRecv() (*AddFileReply, error)
	grpc.ClientStream
}

type aPIAddFileClient struct {
	grpc.ClientStream
}

func (x *aPIAddFileClient) Send(m *AddFileRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *aPIAddFileClient) CloseAndRecv() (*AddFileReply, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(AddFileReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *aPIClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (API_GetClient, error) {
	stream, err := c.cc.NewStream(ctx, &_API_serviceDesc.Streams[1], "/filecoin.ffs.pb.API/Get", opts...)
	if err != nil {
		return nil, err
	}
	x := &aPIGetClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type API_GetClient interface {
	Recv() (*GetReply, error)
	grpc.ClientStream
}

type aPIGetClient struct {
	grpc.ClientStream
}

func (x *aPIGetClient) Recv() (*GetReply, error) {
	m := new(GetReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *aPIClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateReply, error) {
	out := new(CreateReply)
	err := c.cc.Invoke(ctx, "/filecoin.ffs.pb.API/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoReply, error) {
	out := new(InfoReply)
	err := c.cc.Invoke(ctx, "/filecoin.ffs.pb.API/Info", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) Show(ctx context.Context, in *ShowRequest, opts ...grpc.CallOption) (*ShowReply, error) {
	out := new(ShowReply)
	err := c.cc.Invoke(ctx, "/filecoin.ffs.pb.API/Show", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APIServer is the server API for API service.
type APIServer interface {
	AddCid(context.Context, *AddCidRequest) (*AddCidReply, error)
	AddFile(API_AddFileServer) error
	Get(*GetRequest, API_GetServer) error
	Create(context.Context, *CreateRequest) (*CreateReply, error)
	Info(context.Context, *InfoRequest) (*InfoReply, error)
	Show(context.Context, *ShowRequest) (*ShowReply, error)
}

// UnimplementedAPIServer can be embedded to have forward compatible implementations.
type UnimplementedAPIServer struct {
}

func (*UnimplementedAPIServer) AddCid(ctx context.Context, req *AddCidRequest) (*AddCidReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCid not implemented")
}
func (*UnimplementedAPIServer) AddFile(srv API_AddFileServer) error {
	return status.Errorf(codes.Unimplemented, "method AddFile not implemented")
}
func (*UnimplementedAPIServer) Get(req *GetRequest, srv API_GetServer) error {
	return status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedAPIServer) Create(ctx context.Context, req *CreateRequest) (*CreateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedAPIServer) Info(ctx context.Context, req *InfoRequest) (*InfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Info not implemented")
}
func (*UnimplementedAPIServer) Show(ctx context.Context, req *ShowRequest) (*ShowReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Show not implemented")
}

func RegisterAPIServer(s *grpc.Server, srv APIServer) {
	s.RegisterService(&_API_serviceDesc, srv)
}

func _API_AddCid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).AddCid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/filecoin.ffs.pb.API/AddCid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).AddCid(ctx, req.(*AddCidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_AddFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(APIServer).AddFile(&aPIAddFileServer{stream})
}

type API_AddFileServer interface {
	SendAndClose(*AddFileReply) error
	Recv() (*AddFileRequest, error)
	grpc.ServerStream
}

type aPIAddFileServer struct {
	grpc.ServerStream
}

func (x *aPIAddFileServer) SendAndClose(m *AddFileReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *aPIAddFileServer) Recv() (*AddFileRequest, error) {
	m := new(AddFileRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _API_Get_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(APIServer).Get(m, &aPIGetServer{stream})
}

type API_GetServer interface {
	Send(*GetReply) error
	grpc.ServerStream
}

type aPIGetServer struct {
	grpc.ServerStream
}

func (x *aPIGetServer) Send(m *GetReply) error {
	return x.ServerStream.SendMsg(m)
}

func _API_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/filecoin.ffs.pb.API/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/filecoin.ffs.pb.API/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).Info(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_Show_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).Show(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/filecoin.ffs.pb.API/Show",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).Show(ctx, req.(*ShowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _API_serviceDesc = grpc.ServiceDesc{
	ServiceName: "filecoin.ffs.pb.API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddCid",
			Handler:    _API_AddCid_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _API_Create_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _API_Info_Handler,
		},
		{
			MethodName: "Show",
			Handler:    _API_Show_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AddFile",
			Handler:       _API_AddFile_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Get",
			Handler:       _API_Get_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "fps.proto",
}
