// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package rpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MinerScore struct {
	Addr                 string   `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Score                int32    `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MinerScore) Reset()         { *m = MinerScore{} }
func (m *MinerScore) String() string { return proto.CompactTextString(m) }
func (*MinerScore) ProtoMessage()    {}
func (*MinerScore) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *MinerScore) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MinerScore.Unmarshal(m, b)
}
func (m *MinerScore) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MinerScore.Marshal(b, m, deterministic)
}
func (m *MinerScore) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MinerScore.Merge(m, src)
}
func (m *MinerScore) XXX_Size() int {
	return xxx_messageInfo_MinerScore.Size(m)
}
func (m *MinerScore) XXX_DiscardUnknown() {
	xxx_messageInfo_MinerScore.DiscardUnknown(m)
}

var xxx_messageInfo_MinerScore proto.InternalMessageInfo

func (m *MinerScore) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *MinerScore) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

type Index struct {
	TipSetKey            string              `protobuf:"bytes,1,opt,name=tipSetKey,proto3" json:"tipSetKey,omitempty"`
	Miners               map[string]*Slashes `protobuf:"bytes,2,rep,name=miners,proto3" json:"miners,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Index) Reset()         { *m = Index{} }
func (m *Index) String() string { return proto.CompactTextString(m) }
func (*Index) ProtoMessage()    {}
func (*Index) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *Index) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Index.Unmarshal(m, b)
}
func (m *Index) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Index.Marshal(b, m, deterministic)
}
func (m *Index) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Index.Merge(m, src)
}
func (m *Index) XXX_Size() int {
	return xxx_messageInfo_Index.Size(m)
}
func (m *Index) XXX_DiscardUnknown() {
	xxx_messageInfo_Index.DiscardUnknown(m)
}

var xxx_messageInfo_Index proto.InternalMessageInfo

func (m *Index) GetTipSetKey() string {
	if m != nil {
		return m.TipSetKey
	}
	return ""
}

func (m *Index) GetMiners() map[string]*Slashes {
	if m != nil {
		return m.Miners
	}
	return nil
}

type Slashes struct {
	Epochs               []uint64 `protobuf:"varint,1,rep,packed,name=epochs,proto3" json:"epochs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Slashes) Reset()         { *m = Slashes{} }
func (m *Slashes) String() string { return proto.CompactTextString(m) }
func (*Slashes) ProtoMessage()    {}
func (*Slashes) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *Slashes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Slashes.Unmarshal(m, b)
}
func (m *Slashes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Slashes.Marshal(b, m, deterministic)
}
func (m *Slashes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Slashes.Merge(m, src)
}
func (m *Slashes) XXX_Size() int {
	return xxx_messageInfo_Slashes.Size(m)
}
func (m *Slashes) XXX_DiscardUnknown() {
	xxx_messageInfo_Slashes.DiscardUnknown(m)
}

var xxx_messageInfo_Slashes proto.InternalMessageInfo

func (m *Slashes) GetEpochs() []uint64 {
	if m != nil {
		return m.Epochs
	}
	return nil
}

type AddSourceRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Maddr                string   `protobuf:"bytes,2,opt,name=maddr,proto3" json:"maddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddSourceRequest) Reset()         { *m = AddSourceRequest{} }
func (m *AddSourceRequest) String() string { return proto.CompactTextString(m) }
func (*AddSourceRequest) ProtoMessage()    {}
func (*AddSourceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *AddSourceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddSourceRequest.Unmarshal(m, b)
}
func (m *AddSourceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddSourceRequest.Marshal(b, m, deterministic)
}
func (m *AddSourceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddSourceRequest.Merge(m, src)
}
func (m *AddSourceRequest) XXX_Size() int {
	return xxx_messageInfo_AddSourceRequest.Size(m)
}
func (m *AddSourceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddSourceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddSourceRequest proto.InternalMessageInfo

func (m *AddSourceRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AddSourceRequest) GetMaddr() string {
	if m != nil {
		return m.Maddr
	}
	return ""
}

type AddSourceReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddSourceReply) Reset()         { *m = AddSourceReply{} }
func (m *AddSourceReply) String() string { return proto.CompactTextString(m) }
func (*AddSourceReply) ProtoMessage()    {}
func (*AddSourceReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *AddSourceReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddSourceReply.Unmarshal(m, b)
}
func (m *AddSourceReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddSourceReply.Marshal(b, m, deterministic)
}
func (m *AddSourceReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddSourceReply.Merge(m, src)
}
func (m *AddSourceReply) XXX_Size() int {
	return xxx_messageInfo_AddSourceReply.Size(m)
}
func (m *AddSourceReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AddSourceReply.DiscardUnknown(m)
}

var xxx_messageInfo_AddSourceReply proto.InternalMessageInfo

type GetTopMinersRequest struct {
	Limit                int32    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTopMinersRequest) Reset()         { *m = GetTopMinersRequest{} }
func (m *GetTopMinersRequest) String() string { return proto.CompactTextString(m) }
func (*GetTopMinersRequest) ProtoMessage()    {}
func (*GetTopMinersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *GetTopMinersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTopMinersRequest.Unmarshal(m, b)
}
func (m *GetTopMinersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTopMinersRequest.Marshal(b, m, deterministic)
}
func (m *GetTopMinersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTopMinersRequest.Merge(m, src)
}
func (m *GetTopMinersRequest) XXX_Size() int {
	return xxx_messageInfo_GetTopMinersRequest.Size(m)
}
func (m *GetTopMinersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTopMinersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTopMinersRequest proto.InternalMessageInfo

func (m *GetTopMinersRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type GetTopMinersReply struct {
	TopMiners            []*MinerScore `protobuf:"bytes,1,rep,name=topMiners,proto3" json:"topMiners,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetTopMinersReply) Reset()         { *m = GetTopMinersReply{} }
func (m *GetTopMinersReply) String() string { return proto.CompactTextString(m) }
func (*GetTopMinersReply) ProtoMessage()    {}
func (*GetTopMinersReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *GetTopMinersReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTopMinersReply.Unmarshal(m, b)
}
func (m *GetTopMinersReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTopMinersReply.Marshal(b, m, deterministic)
}
func (m *GetTopMinersReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTopMinersReply.Merge(m, src)
}
func (m *GetTopMinersReply) XXX_Size() int {
	return xxx_messageInfo_GetTopMinersReply.Size(m)
}
func (m *GetTopMinersReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTopMinersReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetTopMinersReply proto.InternalMessageInfo

func (m *GetTopMinersReply) GetTopMiners() []*MinerScore {
	if m != nil {
		return m.TopMiners
	}
	return nil
}

func init() {
	proto.RegisterType((*MinerScore)(nil), "reputation.rpc.MinerScore")
	proto.RegisterType((*Index)(nil), "reputation.rpc.Index")
	proto.RegisterMapType((map[string]*Slashes)(nil), "reputation.rpc.Index.MinersEntry")
	proto.RegisterType((*Slashes)(nil), "reputation.rpc.Slashes")
	proto.RegisterType((*AddSourceRequest)(nil), "reputation.rpc.AddSourceRequest")
	proto.RegisterType((*AddSourceReply)(nil), "reputation.rpc.AddSourceReply")
	proto.RegisterType((*GetTopMinersRequest)(nil), "reputation.rpc.GetTopMinersRequest")
	proto.RegisterType((*GetTopMinersReply)(nil), "reputation.rpc.GetTopMinersReply")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 410 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x41, 0x6f, 0x94, 0x40,
	0x18, 0x75, 0xa0, 0xac, 0xe1, 0x5b, 0xb3, 0x59, 0x3f, 0x1b, 0x25, 0xc4, 0x18, 0xc0, 0x0b, 0x89,
	0x91, 0x03, 0x26, 0x66, 0xf5, 0xd6, 0xc6, 0x6a, 0x1a, 0xd3, 0xd8, 0x0c, 0x7b, 0x30, 0xde, 0x28,
	0x8c, 0xe9, 0x44, 0x96, 0x19, 0x87, 0xc1, 0x94, 0xbf, 0xe3, 0x2f, 0xf0, 0xe0, 0x0f, 0x34, 0x0c,
	0x74, 0x97, 0x12, 0xd3, 0xdb, 0x7c, 0x8f, 0xf7, 0xde, 0xbc, 0xf7, 0x31, 0xe0, 0xe6, 0x92, 0x27,
	0x52, 0x09, 0x2d, 0x70, 0xa5, 0x98, 0x6c, 0x75, 0xae, 0xb9, 0xa8, 0x13, 0x25, 0x8b, 0xe8, 0x2d,
	0xc0, 0x05, 0xaf, 0x99, 0xca, 0x0a, 0xa1, 0x18, 0x22, 0x1c, 0xe5, 0x65, 0xa9, 0x3c, 0x12, 0x90,
	0xd8, 0xa5, 0xe6, 0x8c, 0xc7, 0xe0, 0x34, 0xfd, 0x47, 0xcf, 0x0a, 0x48, 0xec, 0xd0, 0x61, 0x88,
	0xfe, 0x12, 0x70, 0xce, 0xeb, 0x92, 0xdd, 0xe0, 0x73, 0x70, 0x35, 0x97, 0x19, 0xd3, 0x9f, 0x59,
	0x37, 0x0a, 0x0f, 0x00, 0xbe, 0x83, 0xc5, 0xae, 0xf7, 0x6f, 0x3c, 0x2b, 0xb0, 0xe3, 0x65, 0x1a,
	0x26, 0x77, 0x03, 0x24, 0xc6, 0x24, 0x31, 0x19, 0x9a, 0xb3, 0x5a, 0xab, 0x8e, 0x8e, 0x02, 0x9f,
	0xc2, 0x72, 0x02, 0xe3, 0x1a, 0xec, 0x1f, 0xfb, 0x1b, 0xfa, 0x23, 0xbe, 0x06, 0xe7, 0x57, 0x5e,
	0xb5, 0x43, 0xb2, 0x65, 0xfa, 0x6c, 0x6e, 0x9d, 0x55, 0x79, 0x73, 0xcd, 0x1a, 0x3a, 0xb0, 0xde,
	0x5b, 0x1b, 0x12, 0x85, 0xf0, 0x70, 0x44, 0xf1, 0x29, 0x2c, 0x98, 0x14, 0xc5, 0x75, 0xe3, 0x91,
	0xc0, 0x8e, 0x8f, 0xe8, 0x38, 0x45, 0x1b, 0x58, 0x9f, 0x94, 0x65, 0x26, 0x5a, 0x55, 0x30, 0xca,
	0x7e, 0xb6, 0xac, 0xd1, 0xb8, 0x02, 0x8b, 0x97, 0xe3, 0xd5, 0x16, 0x2f, 0xfb, 0x9d, 0xec, 0xcc,
	0xa2, 0x2c, 0x03, 0x0d, 0x43, 0xb4, 0x86, 0xd5, 0x44, 0x29, 0xab, 0x2e, 0x7a, 0x05, 0x4f, 0x3e,
	0x31, 0xbd, 0x15, 0x72, 0x28, 0x72, 0x6b, 0x77, 0x0c, 0x4e, 0xc5, 0x77, 0x5c, 0x1b, 0x47, 0x87,
	0x0e, 0x43, 0x74, 0x01, 0x8f, 0xef, 0x92, 0x65, 0xd5, 0xe1, 0x06, 0x5c, 0x7d, 0x8b, 0x98, 0xa0,
	0xcb, 0xd4, 0x9f, 0xf7, 0x3c, 0xfc, 0x40, 0x7a, 0x20, 0xa7, 0x7f, 0x08, 0xd8, 0x27, 0x97, 0xe7,
	0xf8, 0x05, 0xdc, 0x7d, 0x2a, 0x0c, 0xe6, 0xda, 0x79, 0x55, 0xff, 0xc5, 0x3d, 0x8c, 0xbe, 0xd2,
	0x03, 0xfc, 0x0a, 0x8f, 0xa6, 0x39, 0xf1, 0xe5, 0x5c, 0xf1, 0x9f, 0xca, 0x7e, 0x78, 0x3f, 0xc9,
	0x38, 0x9f, 0x7e, 0x80, 0x90, 0x8b, 0x44, 0xb3, 0x1b, 0xcd, 0x2b, 0x96, 0x7c, 0xe7, 0x15, 0x2b,
	0x04, 0xaf, 0xa7, 0x4a, 0x79, 0x75, 0x8a, 0x1f, 0x47, 0x9c, 0xee, 0xe1, 0x4b, 0xf2, 0xcd, 0x56,
	0xb2, 0xf8, 0x6d, 0xd9, 0xdb, 0xed, 0xd9, 0xd5, 0xc2, 0xbc, 0xf4, 0x37, 0xff, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x46, 0xbb, 0xf4, 0x67, 0xf6, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// APIClient is the client API for API service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type APIClient interface {
	AddSource(ctx context.Context, in *AddSourceRequest, opts ...grpc.CallOption) (*AddSourceReply, error)
	GetTopMiners(ctx context.Context, in *GetTopMinersRequest, opts ...grpc.CallOption) (*GetTopMinersReply, error)
}

type aPIClient struct {
	cc *grpc.ClientConn
}

func NewAPIClient(cc *grpc.ClientConn) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) AddSource(ctx context.Context, in *AddSourceRequest, opts ...grpc.CallOption) (*AddSourceReply, error) {
	out := new(AddSourceReply)
	err := c.cc.Invoke(ctx, "/reputation.rpc.API/AddSource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetTopMiners(ctx context.Context, in *GetTopMinersRequest, opts ...grpc.CallOption) (*GetTopMinersReply, error) {
	out := new(GetTopMinersReply)
	err := c.cc.Invoke(ctx, "/reputation.rpc.API/GetTopMiners", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APIServer is the server API for API service.
type APIServer interface {
	AddSource(context.Context, *AddSourceRequest) (*AddSourceReply, error)
	GetTopMiners(context.Context, *GetTopMinersRequest) (*GetTopMinersReply, error)
}

// UnimplementedAPIServer can be embedded to have forward compatible implementations.
type UnimplementedAPIServer struct {
}

func (*UnimplementedAPIServer) AddSource(ctx context.Context, req *AddSourceRequest) (*AddSourceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddSource not implemented")
}
func (*UnimplementedAPIServer) GetTopMiners(ctx context.Context, req *GetTopMinersRequest) (*GetTopMinersReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopMiners not implemented")
}

func RegisterAPIServer(s *grpc.Server, srv APIServer) {
	s.RegisterService(&_API_serviceDesc, srv)
}

func _API_AddSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).AddSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reputation.rpc.API/AddSource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).AddSource(ctx, req.(*AddSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetTopMiners_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopMinersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetTopMiners(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reputation.rpc.API/GetTopMiners",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetTopMiners(ctx, req.(*GetTopMinersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _API_serviceDesc = grpc.ServiceDesc{
	ServiceName: "reputation.rpc.API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddSource",
			Handler:    _API_AddSource_Handler,
		},
		{
			MethodName: "GetTopMiners",
			Handler:    _API_GetTopMiners_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
