// Code generated by protoc-gen-go. DO NOT EDIT.
// source: net/rpc/rpc.proto

package rpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Connectedness int32

const (
	Connectedness_NotConnected  Connectedness = 0
	Connectedness_Connected     Connectedness = 1
	Connectedness_CanConnect    Connectedness = 2
	Connectedness_CannotConnect Connectedness = 3
	Connectedness_Unknown       Connectedness = 4
	Connectedness_Error         Connectedness = 5
)

var Connectedness_name = map[int32]string{
	0: "NotConnected",
	1: "Connected",
	2: "CanConnect",
	3: "CannotConnect",
	4: "Unknown",
	5: "Error",
}

var Connectedness_value = map[string]int32{
	"NotConnected":  0,
	"Connected":     1,
	"CanConnect":    2,
	"CannotConnect": 3,
	"Unknown":       4,
	"Error":         5,
}

func (x Connectedness) String() string {
	return proto.EnumName(Connectedness_name, int32(x))
}

func (Connectedness) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2bae94ba2674ce2b, []int{0}
}

type PeerAddrInfo struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Addrs                []string `protobuf:"bytes,2,rep,name=addrs,proto3" json:"addrs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerAddrInfo) Reset()         { *m = PeerAddrInfo{} }
func (m *PeerAddrInfo) String() string { return proto.CompactTextString(m) }
func (*PeerAddrInfo) ProtoMessage()    {}
func (*PeerAddrInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bae94ba2674ce2b, []int{0}
}

func (m *PeerAddrInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerAddrInfo.Unmarshal(m, b)
}
func (m *PeerAddrInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerAddrInfo.Marshal(b, m, deterministic)
}
func (m *PeerAddrInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerAddrInfo.Merge(m, src)
}
func (m *PeerAddrInfo) XXX_Size() int {
	return xxx_messageInfo_PeerAddrInfo.Size(m)
}
func (m *PeerAddrInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerAddrInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PeerAddrInfo proto.InternalMessageInfo

func (m *PeerAddrInfo) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *PeerAddrInfo) GetAddrs() []string {
	if m != nil {
		return m.Addrs
	}
	return nil
}

type Location struct {
	Country              string   `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	Latitude             float32  `protobuf:"fixed32,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float32  `protobuf:"fixed32,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bae94ba2674ce2b, []int{1}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Location) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Location) GetLongitude() float32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

type PeerInfo struct {
	AddrInfo             *PeerAddrInfo `protobuf:"bytes,1,opt,name=addrInfo,proto3" json:"addrInfo,omitempty"`
	Location             *Location     `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PeerInfo) Reset()         { *m = PeerInfo{} }
func (m *PeerInfo) String() string { return proto.CompactTextString(m) }
func (*PeerInfo) ProtoMessage()    {}
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bae94ba2674ce2b, []int{2}
}

func (m *PeerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerInfo.Unmarshal(m, b)
}
func (m *PeerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerInfo.Marshal(b, m, deterministic)
}
func (m *PeerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerInfo.Merge(m, src)
}
func (m *PeerInfo) XXX_Size() int {
	return xxx_messageInfo_PeerInfo.Size(m)
}
func (m *PeerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PeerInfo proto.InternalMessageInfo

func (m *PeerInfo) GetAddrInfo() *PeerAddrInfo {
	if m != nil {
		return m.AddrInfo
	}
	return nil
}

func (m *PeerInfo) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

type ListenAddrRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListenAddrRequest) Reset()         { *m = ListenAddrRequest{} }
func (m *ListenAddrRequest) String() string { return proto.CompactTextString(m) }
func (*ListenAddrRequest) ProtoMessage()    {}
func (*ListenAddrRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bae94ba2674ce2b, []int{3}
}

func (m *ListenAddrRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListenAddrRequest.Unmarshal(m, b)
}
func (m *ListenAddrRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListenAddrRequest.Marshal(b, m, deterministic)
}
func (m *ListenAddrRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListenAddrRequest.Merge(m, src)
}
func (m *ListenAddrRequest) XXX_Size() int {
	return xxx_messageInfo_ListenAddrRequest.Size(m)
}
func (m *ListenAddrRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListenAddrRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListenAddrRequest proto.InternalMessageInfo

type ListenAddrReply struct {
	AddrInfo             *PeerAddrInfo `protobuf:"bytes,1,opt,name=addrInfo,proto3" json:"addrInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListenAddrReply) Reset()         { *m = ListenAddrReply{} }
func (m *ListenAddrReply) String() string { return proto.CompactTextString(m) }
func (*ListenAddrReply) ProtoMessage()    {}
func (*ListenAddrReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bae94ba2674ce2b, []int{4}
}

func (m *ListenAddrReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListenAddrReply.Unmarshal(m, b)
}
func (m *ListenAddrReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListenAddrReply.Marshal(b, m, deterministic)
}
func (m *ListenAddrReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListenAddrReply.Merge(m, src)
}
func (m *ListenAddrReply) XXX_Size() int {
	return xxx_messageInfo_ListenAddrReply.Size(m)
}
func (m *ListenAddrReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListenAddrReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListenAddrReply proto.InternalMessageInfo

func (m *ListenAddrReply) GetAddrInfo() *PeerAddrInfo {
	if m != nil {
		return m.AddrInfo
	}
	return nil
}

type PeersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeersRequest) Reset()         { *m = PeersRequest{} }
func (m *PeersRequest) String() string { return proto.CompactTextString(m) }
func (*PeersRequest) ProtoMessage()    {}
func (*PeersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bae94ba2674ce2b, []int{5}
}

func (m *PeersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeersRequest.Unmarshal(m, b)
}
func (m *PeersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeersRequest.Marshal(b, m, deterministic)
}
func (m *PeersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeersRequest.Merge(m, src)
}
func (m *PeersRequest) XXX_Size() int {
	return xxx_messageInfo_PeersRequest.Size(m)
}
func (m *PeersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PeersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PeersRequest proto.InternalMessageInfo

type PeersReply struct {
	Peers                []*PeerInfo `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PeersReply) Reset()         { *m = PeersReply{} }
func (m *PeersReply) String() string { return proto.CompactTextString(m) }
func (*PeersReply) ProtoMessage()    {}
func (*PeersReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bae94ba2674ce2b, []int{6}
}

func (m *PeersReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeersReply.Unmarshal(m, b)
}
func (m *PeersReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeersReply.Marshal(b, m, deterministic)
}
func (m *PeersReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeersReply.Merge(m, src)
}
func (m *PeersReply) XXX_Size() int {
	return xxx_messageInfo_PeersReply.Size(m)
}
func (m *PeersReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PeersReply.DiscardUnknown(m)
}

var xxx_messageInfo_PeersReply proto.InternalMessageInfo

func (m *PeersReply) GetPeers() []*PeerInfo {
	if m != nil {
		return m.Peers
	}
	return nil
}

type FindPeerRequest struct {
	PeerID               string   `protobuf:"bytes,1,opt,name=peerID,proto3" json:"peerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindPeerRequest) Reset()         { *m = FindPeerRequest{} }
func (m *FindPeerRequest) String() string { return proto.CompactTextString(m) }
func (*FindPeerRequest) ProtoMessage()    {}
func (*FindPeerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bae94ba2674ce2b, []int{7}
}

func (m *FindPeerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindPeerRequest.Unmarshal(m, b)
}
func (m *FindPeerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindPeerRequest.Marshal(b, m, deterministic)
}
func (m *FindPeerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindPeerRequest.Merge(m, src)
}
func (m *FindPeerRequest) XXX_Size() int {
	return xxx_messageInfo_FindPeerRequest.Size(m)
}
func (m *FindPeerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindPeerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindPeerRequest proto.InternalMessageInfo

func (m *FindPeerRequest) GetPeerID() string {
	if m != nil {
		return m.PeerID
	}
	return ""
}

type FindPeerReply struct {
	PeerInfo             *PeerInfo `protobuf:"bytes,1,opt,name=peerInfo,proto3" json:"peerInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *FindPeerReply) Reset()         { *m = FindPeerReply{} }
func (m *FindPeerReply) String() string { return proto.CompactTextString(m) }
func (*FindPeerReply) ProtoMessage()    {}
func (*FindPeerReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bae94ba2674ce2b, []int{8}
}

func (m *FindPeerReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindPeerReply.Unmarshal(m, b)
}
func (m *FindPeerReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindPeerReply.Marshal(b, m, deterministic)
}
func (m *FindPeerReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindPeerReply.Merge(m, src)
}
func (m *FindPeerReply) XXX_Size() int {
	return xxx_messageInfo_FindPeerReply.Size(m)
}
func (m *FindPeerReply) XXX_DiscardUnknown() {
	xxx_messageInfo_FindPeerReply.DiscardUnknown(m)
}

var xxx_messageInfo_FindPeerReply proto.InternalMessageInfo

func (m *FindPeerReply) GetPeerInfo() *PeerInfo {
	if m != nil {
		return m.PeerInfo
	}
	return nil
}

type ConnectPeerRequest struct {
	PeerInfo             *PeerAddrInfo `protobuf:"bytes,1,opt,name=peerInfo,proto3" json:"peerInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ConnectPeerRequest) Reset()         { *m = ConnectPeerRequest{} }
func (m *ConnectPeerRequest) String() string { return proto.CompactTextString(m) }
func (*ConnectPeerRequest) ProtoMessage()    {}
func (*ConnectPeerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bae94ba2674ce2b, []int{9}
}

func (m *ConnectPeerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectPeerRequest.Unmarshal(m, b)
}
func (m *ConnectPeerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectPeerRequest.Marshal(b, m, deterministic)
}
func (m *ConnectPeerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectPeerRequest.Merge(m, src)
}
func (m *ConnectPeerRequest) XXX_Size() int {
	return xxx_messageInfo_ConnectPeerRequest.Size(m)
}
func (m *ConnectPeerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectPeerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectPeerRequest proto.InternalMessageInfo

func (m *ConnectPeerRequest) GetPeerInfo() *PeerAddrInfo {
	if m != nil {
		return m.PeerInfo
	}
	return nil
}

type ConnectPeerReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectPeerReply) Reset()         { *m = ConnectPeerReply{} }
func (m *ConnectPeerReply) String() string { return proto.CompactTextString(m) }
func (*ConnectPeerReply) ProtoMessage()    {}
func (*ConnectPeerReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bae94ba2674ce2b, []int{10}
}

func (m *ConnectPeerReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectPeerReply.Unmarshal(m, b)
}
func (m *ConnectPeerReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectPeerReply.Marshal(b, m, deterministic)
}
func (m *ConnectPeerReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectPeerReply.Merge(m, src)
}
func (m *ConnectPeerReply) XXX_Size() int {
	return xxx_messageInfo_ConnectPeerReply.Size(m)
}
func (m *ConnectPeerReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectPeerReply.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectPeerReply proto.InternalMessageInfo

type DisconnectPeerRequest struct {
	PeerID               string   `protobuf:"bytes,1,opt,name=peerID,proto3" json:"peerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisconnectPeerRequest) Reset()         { *m = DisconnectPeerRequest{} }
func (m *DisconnectPeerRequest) String() string { return proto.CompactTextString(m) }
func (*DisconnectPeerRequest) ProtoMessage()    {}
func (*DisconnectPeerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bae94ba2674ce2b, []int{11}
}

func (m *DisconnectPeerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisconnectPeerRequest.Unmarshal(m, b)
}
func (m *DisconnectPeerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisconnectPeerRequest.Marshal(b, m, deterministic)
}
func (m *DisconnectPeerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisconnectPeerRequest.Merge(m, src)
}
func (m *DisconnectPeerRequest) XXX_Size() int {
	return xxx_messageInfo_DisconnectPeerRequest.Size(m)
}
func (m *DisconnectPeerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DisconnectPeerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DisconnectPeerRequest proto.InternalMessageInfo

func (m *DisconnectPeerRequest) GetPeerID() string {
	if m != nil {
		return m.PeerID
	}
	return ""
}

type DisconnectPeerReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisconnectPeerReply) Reset()         { *m = DisconnectPeerReply{} }
func (m *DisconnectPeerReply) String() string { return proto.CompactTextString(m) }
func (*DisconnectPeerReply) ProtoMessage()    {}
func (*DisconnectPeerReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bae94ba2674ce2b, []int{12}
}

func (m *DisconnectPeerReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisconnectPeerReply.Unmarshal(m, b)
}
func (m *DisconnectPeerReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisconnectPeerReply.Marshal(b, m, deterministic)
}
func (m *DisconnectPeerReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisconnectPeerReply.Merge(m, src)
}
func (m *DisconnectPeerReply) XXX_Size() int {
	return xxx_messageInfo_DisconnectPeerReply.Size(m)
}
func (m *DisconnectPeerReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DisconnectPeerReply.DiscardUnknown(m)
}

var xxx_messageInfo_DisconnectPeerReply proto.InternalMessageInfo

type ConnectednessRequest struct {
	PeerID               string   `protobuf:"bytes,1,opt,name=peerID,proto3" json:"peerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectednessRequest) Reset()         { *m = ConnectednessRequest{} }
func (m *ConnectednessRequest) String() string { return proto.CompactTextString(m) }
func (*ConnectednessRequest) ProtoMessage()    {}
func (*ConnectednessRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bae94ba2674ce2b, []int{13}
}

func (m *ConnectednessRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectednessRequest.Unmarshal(m, b)
}
func (m *ConnectednessRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectednessRequest.Marshal(b, m, deterministic)
}
func (m *ConnectednessRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectednessRequest.Merge(m, src)
}
func (m *ConnectednessRequest) XXX_Size() int {
	return xxx_messageInfo_ConnectednessRequest.Size(m)
}
func (m *ConnectednessRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectednessRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectednessRequest proto.InternalMessageInfo

func (m *ConnectednessRequest) GetPeerID() string {
	if m != nil {
		return m.PeerID
	}
	return ""
}

type ConnectednessReply struct {
	Connectedness        Connectedness `protobuf:"varint,1,opt,name=connectedness,proto3,enum=net.rpc.Connectedness" json:"connectedness,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ConnectednessReply) Reset()         { *m = ConnectednessReply{} }
func (m *ConnectednessReply) String() string { return proto.CompactTextString(m) }
func (*ConnectednessReply) ProtoMessage()    {}
func (*ConnectednessReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bae94ba2674ce2b, []int{14}
}

func (m *ConnectednessReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectednessReply.Unmarshal(m, b)
}
func (m *ConnectednessReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectednessReply.Marshal(b, m, deterministic)
}
func (m *ConnectednessReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectednessReply.Merge(m, src)
}
func (m *ConnectednessReply) XXX_Size() int {
	return xxx_messageInfo_ConnectednessReply.Size(m)
}
func (m *ConnectednessReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectednessReply.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectednessReply proto.InternalMessageInfo

func (m *ConnectednessReply) GetConnectedness() Connectedness {
	if m != nil {
		return m.Connectedness
	}
	return Connectedness_NotConnected
}

func init() {
	proto.RegisterEnum("net.rpc.Connectedness", Connectedness_name, Connectedness_value)
	proto.RegisterType((*PeerAddrInfo)(nil), "net.rpc.PeerAddrInfo")
	proto.RegisterType((*Location)(nil), "net.rpc.Location")
	proto.RegisterType((*PeerInfo)(nil), "net.rpc.PeerInfo")
	proto.RegisterType((*ListenAddrRequest)(nil), "net.rpc.ListenAddrRequest")
	proto.RegisterType((*ListenAddrReply)(nil), "net.rpc.ListenAddrReply")
	proto.RegisterType((*PeersRequest)(nil), "net.rpc.PeersRequest")
	proto.RegisterType((*PeersReply)(nil), "net.rpc.PeersReply")
	proto.RegisterType((*FindPeerRequest)(nil), "net.rpc.FindPeerRequest")
	proto.RegisterType((*FindPeerReply)(nil), "net.rpc.FindPeerReply")
	proto.RegisterType((*ConnectPeerRequest)(nil), "net.rpc.ConnectPeerRequest")
	proto.RegisterType((*ConnectPeerReply)(nil), "net.rpc.ConnectPeerReply")
	proto.RegisterType((*DisconnectPeerRequest)(nil), "net.rpc.DisconnectPeerRequest")
	proto.RegisterType((*DisconnectPeerReply)(nil), "net.rpc.DisconnectPeerReply")
	proto.RegisterType((*ConnectednessRequest)(nil), "net.rpc.ConnectednessRequest")
	proto.RegisterType((*ConnectednessReply)(nil), "net.rpc.ConnectednessReply")
}

func init() { proto.RegisterFile("net/rpc/rpc.proto", fileDescriptor_2bae94ba2674ce2b) }

var fileDescriptor_2bae94ba2674ce2b = []byte{
	// 552 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x6d, 0x6c, 0xdc, 0x38, 0x93, 0x26, 0x75, 0x26, 0x4d, 0x64, 0xdc, 0x82, 0x22, 0x5f, 0x08,
	0x48, 0x4d, 0xd5, 0x40, 0x6f, 0xa8, 0x12, 0x24, 0x50, 0x45, 0x2a, 0x28, 0xb2, 0xc4, 0x85, 0x03,
	0x92, 0xb1, 0x0d, 0x8a, 0x6a, 0xed, 0x9a, 0xf5, 0x46, 0x28, 0xff, 0x89, 0x1f, 0x89, 0xd6, 0x5e,
	0xaf, 0x3f, 0x9a, 0x08, 0x89, 0x83, 0x0f, 0x33, 0x6f, 0xe6, 0xcd, 0x9b, 0xd9, 0x27, 0xc3, 0x80,
	0x44, 0xfc, 0x8a, 0x25, 0x81, 0xf8, 0x66, 0x09, 0xa3, 0x9c, 0x62, 0x9b, 0x44, 0x7c, 0xc6, 0x92,
	0xc0, 0x7d, 0x03, 0x27, 0xeb, 0x28, 0x62, 0xef, 0xc2, 0x90, 0xad, 0xc8, 0x0f, 0x8a, 0x7d, 0xd0,
	0x56, 0x4b, 0xbb, 0x35, 0x69, 0x4d, 0x3b, 0x9e, 0xb6, 0x5a, 0xe2, 0x19, 0x18, 0x7e, 0x18, 0xb2,
	0xd4, 0xd6, 0x26, 0xfa, 0xb4, 0xe3, 0xe5, 0x81, 0xfb, 0x0d, 0xcc, 0x7b, 0x1a, 0xf8, 0x7c, 0x43,
	0x09, 0xda, 0xd0, 0x0e, 0xe8, 0x96, 0x70, 0xb6, 0x93, 0x6d, 0x45, 0x88, 0x0e, 0x98, 0xb1, 0xcf,
	0x37, 0x7c, 0x1b, 0x46, 0xb6, 0x36, 0x69, 0x4d, 0x35, 0x4f, 0xc5, 0x78, 0x01, 0x9d, 0x98, 0x92,
	0x9f, 0x39, 0xa8, 0x67, 0x60, 0x99, 0x70, 0x63, 0x30, 0x85, 0xaa, 0x4c, 0xd1, 0x35, 0x98, 0xbe,
	0x54, 0x97, 0x0d, 0xe8, 0xce, 0x47, 0x33, 0xa9, 0x7e, 0x56, 0x95, 0xee, 0xa9, 0x32, 0xbc, 0x04,
	0x33, 0x96, 0xf2, 0xb2, 0xc1, 0xdd, 0xf9, 0x40, 0xb5, 0x14, 0xba, 0x3d, 0x55, 0xe2, 0x0e, 0x61,
	0x70, 0xbf, 0x49, 0x79, 0x44, 0x04, 0x95, 0x17, 0xfd, 0xda, 0x46, 0x29, 0x77, 0x97, 0x70, 0x5a,
	0x4d, 0x26, 0xf1, 0xee, 0x3f, 0x94, 0xb8, 0xfd, 0xfc, 0xbc, 0x69, 0xc1, 0x7a, 0x03, 0x20, 0x63,
	0x41, 0xf8, 0x02, 0x8c, 0x44, 0x44, 0x76, 0x6b, 0xa2, 0xd7, 0x44, 0x16, 0xcb, 0x7b, 0x39, 0xee,
	0xbe, 0x84, 0xd3, 0x8f, 0x1b, 0x12, 0x8a, 0xb4, 0x64, 0xc2, 0x31, 0x1c, 0x0b, 0x4c, 0x3d, 0x96,
	0x8c, 0xdc, 0x5b, 0xe8, 0x95, 0xa5, 0x62, 0xc8, 0x25, 0x98, 0x89, 0xa4, 0x93, 0xaa, 0xf7, 0xcc,
	0x51, 0x25, 0xee, 0x1d, 0xe0, 0x82, 0x12, 0x12, 0x05, 0xbc, 0x3a, 0xed, 0xfa, 0x11, 0xc9, 0xa1,
	0xd5, 0x15, 0x11, 0x82, 0x55, 0x23, 0x4a, 0xe2, 0x9d, 0x7b, 0x05, 0xa3, 0xe5, 0x26, 0x0d, 0x1e,
	0xf3, 0x1f, 0xda, 0x66, 0x04, 0xc3, 0x66, 0x83, 0xe0, 0x99, 0xc1, 0x99, 0xe4, 0x8e, 0x42, 0x12,
	0xa5, 0xe9, 0xbf, 0x68, 0x3c, 0xb5, 0x54, 0x51, 0x2f, 0x2e, 0xf3, 0x16, 0x7a, 0x41, 0x35, 0x9b,
	0x35, 0xf5, 0xe7, 0x63, 0xb5, 0x59, 0xbd, 0xa7, 0x5e, 0xfc, 0xea, 0x01, 0x7a, 0x35, 0x1c, 0x2d,
	0x38, 0xf9, 0x4c, 0xb9, 0xca, 0x59, 0x47, 0xd8, 0x83, 0x4e, 0x19, 0xb6, 0xb0, 0x0f, 0xb0, 0xf0,
	0x89, 0xcc, 0x58, 0x1a, 0x0e, 0xa0, 0xb7, 0xf0, 0x09, 0x51, 0x3d, 0x96, 0x8e, 0x5d, 0x68, 0x7f,
	0x21, 0x0f, 0x84, 0xfe, 0x26, 0xd6, 0x13, 0xec, 0x80, 0xf1, 0x81, 0x31, 0xca, 0x2c, 0x63, 0xfe,
	0x47, 0x07, 0xdd, 0x5b, 0x2f, 0x70, 0x09, 0x50, 0xba, 0x12, 0x9d, 0xd2, 0xd5, 0x4d, 0xff, 0x3a,
	0xf6, 0x5e, 0x4c, 0x1c, 0xef, 0x08, 0x6f, 0xc0, 0xc8, 0x5c, 0x88, 0xf5, 0x47, 0x2c, 0xce, 0xe8,
	0x0c, 0x9b, 0xe9, 0xbc, 0xed, 0x16, 0xcc, 0xc2, 0x5a, 0x58, 0xd2, 0x37, 0x8c, 0xe9, 0x8c, 0xf7,
	0x20, 0x79, 0xff, 0x1d, 0x74, 0x2b, 0x8e, 0xc0, 0xf3, 0xe6, 0x9d, 0xab, 0x2c, 0x4f, 0xf7, 0x83,
	0x39, 0xd1, 0x1a, 0xfa, 0x75, 0x57, 0xe0, 0x73, 0x55, 0xbe, 0xd7, 0x5f, 0xce, 0xc5, 0x41, 0x3c,
	0x67, 0xfc, 0xd4, 0x7c, 0xcc, 0x67, 0x07, 0x4c, 0x20, 0xf9, 0xce, 0x0f, 0xc1, 0x19, 0xdd, 0x7b,
	0xe3, 0xab, 0xce, 0x92, 0xe0, 0xfb, 0x71, 0xf6, 0xb3, 0x7d, 0xfd, 0x37, 0x00, 0x00, 0xff, 0xff,
	0xc9, 0xcb, 0x70, 0x81, 0x81, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RPCClient is the client API for RPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RPCClient interface {
	ListenAddr(ctx context.Context, in *ListenAddrRequest, opts ...grpc.CallOption) (*ListenAddrReply, error)
	Peers(ctx context.Context, in *PeersRequest, opts ...grpc.CallOption) (*PeersReply, error)
	FindPeer(ctx context.Context, in *FindPeerRequest, opts ...grpc.CallOption) (*FindPeerReply, error)
	ConnectPeer(ctx context.Context, in *ConnectPeerRequest, opts ...grpc.CallOption) (*ConnectPeerReply, error)
	DisconnectPeer(ctx context.Context, in *DisconnectPeerRequest, opts ...grpc.CallOption) (*DisconnectPeerReply, error)
	Connectedness(ctx context.Context, in *ConnectednessRequest, opts ...grpc.CallOption) (*ConnectednessReply, error)
}

type rPCClient struct {
	cc *grpc.ClientConn
}

func NewRPCClient(cc *grpc.ClientConn) RPCClient {
	return &rPCClient{cc}
}

func (c *rPCClient) ListenAddr(ctx context.Context, in *ListenAddrRequest, opts ...grpc.CallOption) (*ListenAddrReply, error) {
	out := new(ListenAddrReply)
	err := c.cc.Invoke(ctx, "/net.rpc.RPC/ListenAddr", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCClient) Peers(ctx context.Context, in *PeersRequest, opts ...grpc.CallOption) (*PeersReply, error) {
	out := new(PeersReply)
	err := c.cc.Invoke(ctx, "/net.rpc.RPC/Peers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCClient) FindPeer(ctx context.Context, in *FindPeerRequest, opts ...grpc.CallOption) (*FindPeerReply, error) {
	out := new(FindPeerReply)
	err := c.cc.Invoke(ctx, "/net.rpc.RPC/FindPeer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCClient) ConnectPeer(ctx context.Context, in *ConnectPeerRequest, opts ...grpc.CallOption) (*ConnectPeerReply, error) {
	out := new(ConnectPeerReply)
	err := c.cc.Invoke(ctx, "/net.rpc.RPC/ConnectPeer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCClient) DisconnectPeer(ctx context.Context, in *DisconnectPeerRequest, opts ...grpc.CallOption) (*DisconnectPeerReply, error) {
	out := new(DisconnectPeerReply)
	err := c.cc.Invoke(ctx, "/net.rpc.RPC/DisconnectPeer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCClient) Connectedness(ctx context.Context, in *ConnectednessRequest, opts ...grpc.CallOption) (*ConnectednessReply, error) {
	out := new(ConnectednessReply)
	err := c.cc.Invoke(ctx, "/net.rpc.RPC/Connectedness", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RPCServer is the server API for RPC service.
type RPCServer interface {
	ListenAddr(context.Context, *ListenAddrRequest) (*ListenAddrReply, error)
	Peers(context.Context, *PeersRequest) (*PeersReply, error)
	FindPeer(context.Context, *FindPeerRequest) (*FindPeerReply, error)
	ConnectPeer(context.Context, *ConnectPeerRequest) (*ConnectPeerReply, error)
	DisconnectPeer(context.Context, *DisconnectPeerRequest) (*DisconnectPeerReply, error)
	Connectedness(context.Context, *ConnectednessRequest) (*ConnectednessReply, error)
}

// UnimplementedRPCServer can be embedded to have forward compatible implementations.
type UnimplementedRPCServer struct {
}

func (*UnimplementedRPCServer) ListenAddr(ctx context.Context, req *ListenAddrRequest) (*ListenAddrReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListenAddr not implemented")
}
func (*UnimplementedRPCServer) Peers(ctx context.Context, req *PeersRequest) (*PeersReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Peers not implemented")
}
func (*UnimplementedRPCServer) FindPeer(ctx context.Context, req *FindPeerRequest) (*FindPeerReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindPeer not implemented")
}
func (*UnimplementedRPCServer) ConnectPeer(ctx context.Context, req *ConnectPeerRequest) (*ConnectPeerReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConnectPeer not implemented")
}
func (*UnimplementedRPCServer) DisconnectPeer(ctx context.Context, req *DisconnectPeerRequest) (*DisconnectPeerReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisconnectPeer not implemented")
}
func (*UnimplementedRPCServer) Connectedness(ctx context.Context, req *ConnectednessRequest) (*ConnectednessReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Connectedness not implemented")
}

func RegisterRPCServer(s *grpc.Server, srv RPCServer) {
	s.RegisterService(&_RPC_serviceDesc, srv)
}

func _RPC_ListenAddr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListenAddrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).ListenAddr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/net.rpc.RPC/ListenAddr",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).ListenAddr(ctx, req.(*ListenAddrRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPC_Peers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).Peers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/net.rpc.RPC/Peers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).Peers(ctx, req.(*PeersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPC_FindPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindPeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).FindPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/net.rpc.RPC/FindPeer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).FindPeer(ctx, req.(*FindPeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPC_ConnectPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectPeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).ConnectPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/net.rpc.RPC/ConnectPeer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).ConnectPeer(ctx, req.(*ConnectPeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPC_DisconnectPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectPeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).DisconnectPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/net.rpc.RPC/DisconnectPeer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).DisconnectPeer(ctx, req.(*DisconnectPeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPC_Connectedness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectednessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).Connectedness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/net.rpc.RPC/Connectedness",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).Connectedness(ctx, req.(*ConnectednessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "net.rpc.RPC",
	HandlerType: (*RPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListenAddr",
			Handler:    _RPC_ListenAddr_Handler,
		},
		{
			MethodName: "Peers",
			Handler:    _RPC_Peers_Handler,
		},
		{
			MethodName: "FindPeer",
			Handler:    _RPC_FindPeer_Handler,
		},
		{
			MethodName: "ConnectPeer",
			Handler:    _RPC_ConnectPeer_Handler,
		},
		{
			MethodName: "DisconnectPeer",
			Handler:    _RPC_DisconnectPeer_Handler,
		},
		{
			MethodName: "Connectedness",
			Handler:    _RPC_Connectedness_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "net/rpc/rpc.proto",
}
