// Code generated by protoc-gen-go. DO NOT EDIT.
// source: index/ask/rpc/rpc.proto

package rpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Query struct {
	MaxPrice             uint64   `protobuf:"varint,1,opt,name=maxPrice,proto3" json:"maxPrice,omitempty"`
	PieceSize            uint64   `protobuf:"varint,2,opt,name=pieceSize,proto3" json:"pieceSize,omitempty"`
	Limit                int32    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32    `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Query) Reset()         { *m = Query{} }
func (m *Query) String() string { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()    {}
func (*Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_66233fd8cd37f05d, []int{0}
}

func (m *Query) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Query.Unmarshal(m, b)
}
func (m *Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Query.Marshal(b, m, deterministic)
}
func (m *Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Query.Merge(m, src)
}
func (m *Query) XXX_Size() int {
	return xxx_messageInfo_Query.Size(m)
}
func (m *Query) XXX_DiscardUnknown() {
	xxx_messageInfo_Query.DiscardUnknown(m)
}

var xxx_messageInfo_Query proto.InternalMessageInfo

func (m *Query) GetMaxPrice() uint64 {
	if m != nil {
		return m.MaxPrice
	}
	return 0
}

func (m *Query) GetPieceSize() uint64 {
	if m != nil {
		return m.PieceSize
	}
	return 0
}

func (m *Query) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Query) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type StorageAsk struct {
	Price                uint64   `protobuf:"varint,1,opt,name=price,proto3" json:"price,omitempty"`
	MinPieceSize         uint64   `protobuf:"varint,2,opt,name=minPieceSize,proto3" json:"minPieceSize,omitempty"`
	Miner                string   `protobuf:"bytes,3,opt,name=miner,proto3" json:"miner,omitempty"`
	Timestamp            int64    `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Expiry               int64    `protobuf:"varint,5,opt,name=expiry,proto3" json:"expiry,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StorageAsk) Reset()         { *m = StorageAsk{} }
func (m *StorageAsk) String() string { return proto.CompactTextString(m) }
func (*StorageAsk) ProtoMessage()    {}
func (*StorageAsk) Descriptor() ([]byte, []int) {
	return fileDescriptor_66233fd8cd37f05d, []int{1}
}

func (m *StorageAsk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageAsk.Unmarshal(m, b)
}
func (m *StorageAsk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageAsk.Marshal(b, m, deterministic)
}
func (m *StorageAsk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageAsk.Merge(m, src)
}
func (m *StorageAsk) XXX_Size() int {
	return xxx_messageInfo_StorageAsk.Size(m)
}
func (m *StorageAsk) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageAsk.DiscardUnknown(m)
}

var xxx_messageInfo_StorageAsk proto.InternalMessageInfo

func (m *StorageAsk) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *StorageAsk) GetMinPieceSize() uint64 {
	if m != nil {
		return m.MinPieceSize
	}
	return 0
}

func (m *StorageAsk) GetMiner() string {
	if m != nil {
		return m.Miner
	}
	return ""
}

func (m *StorageAsk) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *StorageAsk) GetExpiry() int64 {
	if m != nil {
		return m.Expiry
	}
	return 0
}

type Index struct {
	LastUpdated          int64                  `protobuf:"varint,1,opt,name=lastUpdated,proto3" json:"lastUpdated,omitempty"`
	StorageMedianPrice   uint64                 `protobuf:"varint,2,opt,name=storageMedianPrice,proto3" json:"storageMedianPrice,omitempty"`
	Storage              map[string]*StorageAsk `protobuf:"bytes,3,rep,name=storage,proto3" json:"storage,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Index) Reset()         { *m = Index{} }
func (m *Index) String() string { return proto.CompactTextString(m) }
func (*Index) ProtoMessage()    {}
func (*Index) Descriptor() ([]byte, []int) {
	return fileDescriptor_66233fd8cd37f05d, []int{2}
}

func (m *Index) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Index.Unmarshal(m, b)
}
func (m *Index) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Index.Marshal(b, m, deterministic)
}
func (m *Index) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Index.Merge(m, src)
}
func (m *Index) XXX_Size() int {
	return xxx_messageInfo_Index.Size(m)
}
func (m *Index) XXX_DiscardUnknown() {
	xxx_messageInfo_Index.DiscardUnknown(m)
}

var xxx_messageInfo_Index proto.InternalMessageInfo

func (m *Index) GetLastUpdated() int64 {
	if m != nil {
		return m.LastUpdated
	}
	return 0
}

func (m *Index) GetStorageMedianPrice() uint64 {
	if m != nil {
		return m.StorageMedianPrice
	}
	return 0
}

func (m *Index) GetStorage() map[string]*StorageAsk {
	if m != nil {
		return m.Storage
	}
	return nil
}

type GetRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_66233fd8cd37f05d, []int{3}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

type GetReply struct {
	Index                *Index   `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReply) Reset()         { *m = GetReply{} }
func (m *GetReply) String() string { return proto.CompactTextString(m) }
func (*GetReply) ProtoMessage()    {}
func (*GetReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_66233fd8cd37f05d, []int{4}
}

func (m *GetReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReply.Unmarshal(m, b)
}
func (m *GetReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReply.Marshal(b, m, deterministic)
}
func (m *GetReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReply.Merge(m, src)
}
func (m *GetReply) XXX_Size() int {
	return xxx_messageInfo_GetReply.Size(m)
}
func (m *GetReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetReply proto.InternalMessageInfo

func (m *GetReply) GetIndex() *Index {
	if m != nil {
		return m.Index
	}
	return nil
}

type QueryRequest struct {
	Query                *Query   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryRequest) Reset()         { *m = QueryRequest{} }
func (m *QueryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()    {}
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_66233fd8cd37f05d, []int{5}
}

func (m *QueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRequest.Unmarshal(m, b)
}
func (m *QueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRequest.Marshal(b, m, deterministic)
}
func (m *QueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRequest.Merge(m, src)
}
func (m *QueryRequest) XXX_Size() int {
	return xxx_messageInfo_QueryRequest.Size(m)
}
func (m *QueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRequest proto.InternalMessageInfo

func (m *QueryRequest) GetQuery() *Query {
	if m != nil {
		return m.Query
	}
	return nil
}

type QueryReply struct {
	Asks                 []*StorageAsk `protobuf:"bytes,1,rep,name=asks,proto3" json:"asks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *QueryReply) Reset()         { *m = QueryReply{} }
func (m *QueryReply) String() string { return proto.CompactTextString(m) }
func (*QueryReply) ProtoMessage()    {}
func (*QueryReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_66233fd8cd37f05d, []int{6}
}

func (m *QueryReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryReply.Unmarshal(m, b)
}
func (m *QueryReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryReply.Marshal(b, m, deterministic)
}
func (m *QueryReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryReply.Merge(m, src)
}
func (m *QueryReply) XXX_Size() int {
	return xxx_messageInfo_QueryReply.Size(m)
}
func (m *QueryReply) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryReply.DiscardUnknown(m)
}

var xxx_messageInfo_QueryReply proto.InternalMessageInfo

func (m *QueryReply) GetAsks() []*StorageAsk {
	if m != nil {
		return m.Asks
	}
	return nil
}

func init() {
	proto.RegisterType((*Query)(nil), "index.ask.rpc.Query")
	proto.RegisterType((*StorageAsk)(nil), "index.ask.rpc.StorageAsk")
	proto.RegisterType((*Index)(nil), "index.ask.rpc.Index")
	proto.RegisterMapType((map[string]*StorageAsk)(nil), "index.ask.rpc.Index.StorageEntry")
	proto.RegisterType((*GetRequest)(nil), "index.ask.rpc.GetRequest")
	proto.RegisterType((*GetReply)(nil), "index.ask.rpc.GetReply")
	proto.RegisterType((*QueryRequest)(nil), "index.ask.rpc.QueryRequest")
	proto.RegisterType((*QueryReply)(nil), "index.ask.rpc.QueryReply")
}

func init() { proto.RegisterFile("index/ask/rpc/rpc.proto", fileDescriptor_66233fd8cd37f05d) }

var fileDescriptor_66233fd8cd37f05d = []byte{
	// 449 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x25, 0x73, 0x33, 0xd6, 0xdb, 0x22, 0x21, 0x6b, 0x62, 0x59, 0xe1, 0xa1, 0xf8, 0xa9, 0x42,
	0x22, 0x95, 0x8a, 0x84, 0xd0, 0xfa, 0x34, 0x10, 0x9a, 0x78, 0x40, 0x2a, 0x9e, 0xf6, 0xc2, 0x9b,
	0x49, 0xef, 0x90, 0x95, 0x2f, 0xcf, 0x76, 0x51, 0xc3, 0x3b, 0x7f, 0x80, 0xff, 0xc9, 0x7f, 0x40,
	0xb6, 0x33, 0xd2, 0x56, 0x61, 0x0f, 0x91, 0x72, 0xee, 0xb9, 0xe7, 0x9e, 0xe3, 0x1b, 0x07, 0xce,
	0x64, 0xb5, 0xc6, 0xed, 0x5c, 0x98, 0x7c, 0xae, 0x55, 0xe6, 0x9e, 0x54, 0xe9, 0xda, 0xd6, 0xf4,
	0x89, 0x27, 0x52, 0x61, 0xf2, 0x54, 0xab, 0x8c, 0xd5, 0x10, 0x7f, 0xd9, 0xa0, 0x6e, 0xe8, 0x04,
	0x4e, 0x4a, 0xb1, 0x5d, 0x69, 0x99, 0x61, 0x12, 0x4d, 0xa3, 0xd9, 0x80, 0xff, 0xc3, 0xf4, 0x05,
	0x0c, 0x95, 0xc4, 0x0c, 0xaf, 0xe5, 0x4f, 0x4c, 0x8e, 0x3c, 0xd9, 0x15, 0xe8, 0x29, 0xc4, 0x85,
	0x2c, 0xa5, 0x4d, 0xc8, 0x34, 0x9a, 0xc5, 0x3c, 0x00, 0xfa, 0x0c, 0x8e, 0xeb, 0xdb, 0x5b, 0x83,
	0x36, 0x19, 0xf8, 0x72, 0x8b, 0xd8, 0xef, 0x08, 0xe0, 0xda, 0xd6, 0x5a, 0x7c, 0xc7, 0x4b, 0x93,
	0x3b, 0xb1, 0xda, 0xf1, 0x0c, 0x80, 0x32, 0x18, 0x97, 0xb2, 0x5a, 0x1d, 0x78, 0xee, 0xd5, 0x9c,
	0xb2, 0x94, 0x15, 0x6a, 0x6f, 0x3b, 0xe4, 0x01, 0xb8, 0xa8, 0x56, 0x96, 0x68, 0xac, 0x28, 0x95,
	0x77, 0x26, 0xbc, 0x2b, 0xb8, 0x50, 0xb8, 0x55, 0x52, 0x37, 0x49, 0xec, 0xa9, 0x16, 0xb1, 0x3f,
	0x11, 0xc4, 0x9f, 0xdc, 0x5e, 0xe8, 0x14, 0x46, 0x85, 0x30, 0xf6, 0x46, 0xad, 0x85, 0xc5, 0xb5,
	0x4f, 0x45, 0xf8, 0x6e, 0x89, 0xa6, 0x40, 0x4d, 0xc8, 0xff, 0x19, 0xd7, 0x52, 0x54, 0x61, 0x65,
	0x21, 0x61, 0x0f, 0x43, 0x97, 0xf0, 0xb8, 0xad, 0x26, 0x64, 0x4a, 0x66, 0xa3, 0xc5, 0xcb, 0x74,
	0xef, 0x13, 0xa4, 0xde, 0x38, 0x6d, 0x77, 0xf2, 0xb1, 0xb2, 0xba, 0xe1, 0xf7, 0x8a, 0xc9, 0x0d,
	0x8c, 0x77, 0x09, 0xfa, 0x14, 0x48, 0x8e, 0x8d, 0x8f, 0x35, 0xe4, 0xee, 0x95, 0xce, 0x21, 0xfe,
	0x21, 0x8a, 0x4d, 0x48, 0x30, 0x5a, 0x9c, 0x1f, 0x0c, 0xef, 0x56, 0xcd, 0x43, 0xdf, 0xc5, 0xd1,
	0xbb, 0x88, 0x8d, 0x01, 0xae, 0xd0, 0x72, 0xbc, 0xdb, 0xa0, 0xb1, 0xec, 0x2d, 0x9c, 0x78, 0xa4,
	0x8a, 0x86, 0xbe, 0x82, 0xd8, 0x0f, 0xf0, 0x16, 0xa3, 0xc5, 0x69, 0x5f, 0x56, 0x1e, 0x5a, 0xd8,
	0x05, 0x8c, 0xfd, 0xdd, 0x69, 0xe7, 0x38, 0xed, 0x9d, 0xc3, 0xff, 0xd1, 0x86, 0xde, 0xd0, 0xc2,
	0x96, 0x00, 0xad, 0xd6, 0xb9, 0xbe, 0x86, 0x81, 0x30, 0xb9, 0x49, 0x22, 0xbf, 0xa0, 0x07, 0xce,
	0xe0, 0xdb, 0x16, 0xbf, 0x22, 0x20, 0x7c, 0xf5, 0x81, 0x2e, 0x81, 0x5c, 0xa1, 0xa5, 0x87, 0xfd,
	0xdd, 0xd1, 0x26, 0x67, 0x7d, 0x94, 0x2a, 0x1a, 0xf6, 0x88, 0x5e, 0xde, 0xdf, 0xfc, 0xe7, 0xbd,
	0x39, 0xdb, 0x01, 0xe7, 0xfd, 0xa4, 0x1f, 0xf1, 0x3e, 0xfe, 0x4a, 0xb4, 0xca, 0xbe, 0x1d, 0xfb,
	0x3f, 0xeb, 0xcd, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x12, 0xbb, 0x99, 0x16, 0x74, 0x03, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RPCClient is the client API for RPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RPCClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetReply, error)
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryReply, error)
}

type rPCClient struct {
	cc *grpc.ClientConn
}

func NewRPCClient(cc *grpc.ClientConn) RPCClient {
	return &rPCClient{cc}
}

func (c *rPCClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetReply, error) {
	out := new(GetReply)
	err := c.cc.Invoke(ctx, "/index.ask.rpc.RPC/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryReply, error) {
	out := new(QueryReply)
	err := c.cc.Invoke(ctx, "/index.ask.rpc.RPC/Query", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RPCServer is the server API for RPC service.
type RPCServer interface {
	Get(context.Context, *GetRequest) (*GetReply, error)
	Query(context.Context, *QueryRequest) (*QueryReply, error)
}

// UnimplementedRPCServer can be embedded to have forward compatible implementations.
type UnimplementedRPCServer struct {
}

func (*UnimplementedRPCServer) Get(ctx context.Context, req *GetRequest) (*GetReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedRPCServer) Query(ctx context.Context, req *QueryRequest) (*QueryReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}

func RegisterRPCServer(s *grpc.Server, srv RPCServer) {
	s.RegisterService(&_RPC_serviceDesc, srv)
}

func _RPC_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/index.ask.rpc.RPC/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPC_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/index.ask.rpc.RPC/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "index.ask.rpc.RPC",
	HandlerType: (*RPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _RPC_Get_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _RPC_Query_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "index/ask/rpc/rpc.proto",
}
