// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package rpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Index struct {
	Meta                 *MetaIndex  `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Chain                *ChainIndex `protobuf:"bytes,2,opt,name=chain,proto3" json:"chain,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Index) Reset()         { *m = Index{} }
func (m *Index) String() string { return proto.CompactTextString(m) }
func (*Index) ProtoMessage()    {}
func (*Index) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *Index) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Index.Unmarshal(m, b)
}
func (m *Index) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Index.Marshal(b, m, deterministic)
}
func (m *Index) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Index.Merge(m, src)
}
func (m *Index) XXX_Size() int {
	return xxx_messageInfo_Index.Size(m)
}
func (m *Index) XXX_DiscardUnknown() {
	xxx_messageInfo_Index.DiscardUnknown(m)
}

var xxx_messageInfo_Index proto.InternalMessageInfo

func (m *Index) GetMeta() *MetaIndex {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *Index) GetChain() *ChainIndex {
	if m != nil {
		return m.Chain
	}
	return nil
}

type ChainIndex struct {
	LastUpdated          int64             `protobuf:"varint,1,opt,name=lastUpdated,proto3" json:"lastUpdated,omitempty"`
	Power                map[string]*Power `protobuf:"bytes,2,rep,name=power,proto3" json:"power,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ChainIndex) Reset()         { *m = ChainIndex{} }
func (m *ChainIndex) String() string { return proto.CompactTextString(m) }
func (*ChainIndex) ProtoMessage()    {}
func (*ChainIndex) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *ChainIndex) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainIndex.Unmarshal(m, b)
}
func (m *ChainIndex) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainIndex.Marshal(b, m, deterministic)
}
func (m *ChainIndex) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainIndex.Merge(m, src)
}
func (m *ChainIndex) XXX_Size() int {
	return xxx_messageInfo_ChainIndex.Size(m)
}
func (m *ChainIndex) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainIndex.DiscardUnknown(m)
}

var xxx_messageInfo_ChainIndex proto.InternalMessageInfo

func (m *ChainIndex) GetLastUpdated() int64 {
	if m != nil {
		return m.LastUpdated
	}
	return 0
}

func (m *ChainIndex) GetPower() map[string]*Power {
	if m != nil {
		return m.Power
	}
	return nil
}

type Power struct {
	Power                uint64   `protobuf:"varint,1,opt,name=power,proto3" json:"power,omitempty"`
	Relative             float32  `protobuf:"fixed32,2,opt,name=relative,proto3" json:"relative,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Power) Reset()         { *m = Power{} }
func (m *Power) String() string { return proto.CompactTextString(m) }
func (*Power) ProtoMessage()    {}
func (*Power) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *Power) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Power.Unmarshal(m, b)
}
func (m *Power) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Power.Marshal(b, m, deterministic)
}
func (m *Power) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Power.Merge(m, src)
}
func (m *Power) XXX_Size() int {
	return xxx_messageInfo_Power.Size(m)
}
func (m *Power) XXX_DiscardUnknown() {
	xxx_messageInfo_Power.DiscardUnknown(m)
}

var xxx_messageInfo_Power proto.InternalMessageInfo

func (m *Power) GetPower() uint64 {
	if m != nil {
		return m.Power
	}
	return 0
}

func (m *Power) GetRelative() float32 {
	if m != nil {
		return m.Relative
	}
	return 0
}

type MetaIndex struct {
	Online               uint32           `protobuf:"varint,1,opt,name=online,proto3" json:"online,omitempty"`
	Offline              uint32           `protobuf:"varint,2,opt,name=offline,proto3" json:"offline,omitempty"`
	Info                 map[string]*Meta `protobuf:"bytes,3,rep,name=info,proto3" json:"info,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *MetaIndex) Reset()         { *m = MetaIndex{} }
func (m *MetaIndex) String() string { return proto.CompactTextString(m) }
func (*MetaIndex) ProtoMessage()    {}
func (*MetaIndex) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *MetaIndex) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaIndex.Unmarshal(m, b)
}
func (m *MetaIndex) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaIndex.Marshal(b, m, deterministic)
}
func (m *MetaIndex) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaIndex.Merge(m, src)
}
func (m *MetaIndex) XXX_Size() int {
	return xxx_messageInfo_MetaIndex.Size(m)
}
func (m *MetaIndex) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaIndex.DiscardUnknown(m)
}

var xxx_messageInfo_MetaIndex proto.InternalMessageInfo

func (m *MetaIndex) GetOnline() uint32 {
	if m != nil {
		return m.Online
	}
	return 0
}

func (m *MetaIndex) GetOffline() uint32 {
	if m != nil {
		return m.Offline
	}
	return 0
}

func (m *MetaIndex) GetInfo() map[string]*Meta {
	if m != nil {
		return m.Info
	}
	return nil
}

type Meta struct {
	LastUpdated          int64     `protobuf:"varint,1,opt,name=lastUpdated,proto3" json:"lastUpdated,omitempty"`
	UserAgent            string    `protobuf:"bytes,2,opt,name=userAgent,proto3" json:"userAgent,omitempty"`
	Location             *Location `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Online               bool      `protobuf:"varint,4,opt,name=online,proto3" json:"online,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Meta) Reset()         { *m = Meta{} }
func (m *Meta) String() string { return proto.CompactTextString(m) }
func (*Meta) ProtoMessage()    {}
func (*Meta) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *Meta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Meta.Unmarshal(m, b)
}
func (m *Meta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Meta.Marshal(b, m, deterministic)
}
func (m *Meta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Meta.Merge(m, src)
}
func (m *Meta) XXX_Size() int {
	return xxx_messageInfo_Meta.Size(m)
}
func (m *Meta) XXX_DiscardUnknown() {
	xxx_messageInfo_Meta.DiscardUnknown(m)
}

var xxx_messageInfo_Meta proto.InternalMessageInfo

func (m *Meta) GetLastUpdated() int64 {
	if m != nil {
		return m.LastUpdated
	}
	return 0
}

func (m *Meta) GetUserAgent() string {
	if m != nil {
		return m.UserAgent
	}
	return ""
}

func (m *Meta) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Meta) GetOnline() bool {
	if m != nil {
		return m.Online
	}
	return false
}

type Location struct {
	Country              string   `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	Longitude            float32  `protobuf:"fixed32,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude             float32  `protobuf:"fixed32,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Location) GetLongitude() float32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *Location) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

type GetRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

type GetReply struct {
	Index                *Index   `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReply) Reset()         { *m = GetReply{} }
func (m *GetReply) String() string { return proto.CompactTextString(m) }
func (*GetReply) ProtoMessage()    {}
func (*GetReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7}
}

func (m *GetReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReply.Unmarshal(m, b)
}
func (m *GetReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReply.Marshal(b, m, deterministic)
}
func (m *GetReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReply.Merge(m, src)
}
func (m *GetReply) XXX_Size() int {
	return xxx_messageInfo_GetReply.Size(m)
}
func (m *GetReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetReply proto.InternalMessageInfo

func (m *GetReply) GetIndex() *Index {
	if m != nil {
		return m.Index
	}
	return nil
}

func init() {
	proto.RegisterType((*Index)(nil), "index.miner.rpc.Index")
	proto.RegisterType((*ChainIndex)(nil), "index.miner.rpc.ChainIndex")
	proto.RegisterMapType((map[string]*Power)(nil), "index.miner.rpc.ChainIndex.PowerEntry")
	proto.RegisterType((*Power)(nil), "index.miner.rpc.Power")
	proto.RegisterType((*MetaIndex)(nil), "index.miner.rpc.MetaIndex")
	proto.RegisterMapType((map[string]*Meta)(nil), "index.miner.rpc.MetaIndex.InfoEntry")
	proto.RegisterType((*Meta)(nil), "index.miner.rpc.Meta")
	proto.RegisterType((*Location)(nil), "index.miner.rpc.Location")
	proto.RegisterType((*GetRequest)(nil), "index.miner.rpc.GetRequest")
	proto.RegisterType((*GetReply)(nil), "index.miner.rpc.GetReply")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 473 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x51, 0x8b, 0xd3, 0x40,
	0x10, 0x36, 0xd9, 0xe4, 0x4c, 0xa6, 0x8a, 0xb2, 0xe8, 0x91, 0x8b, 0x3e, 0x94, 0x20, 0x52, 0x50,
	0x02, 0x56, 0x84, 0x2a, 0x82, 0x9c, 0xa2, 0x47, 0x41, 0xa5, 0x2c, 0xf8, 0xe2, 0x83, 0xb0, 0xa6,
	0xdb, 0x73, 0x35, 0xb7, 0x1b, 0xb7, 0x9b, 0xd3, 0xfe, 0x10, 0xff, 0x8e, 0xaf, 0xfe, 0x2d, 0xd9,
	0x49, 0xd2, 0x54, 0x53, 0xe5, 0xde, 0x32, 0xdf, 0x7c, 0x33, 0xdf, 0xce, 0x37, 0x19, 0x88, 0x79,
	0x25, 0xf3, 0xca, 0x68, 0xab, 0xe9, 0x35, 0xa9, 0x96, 0xe2, 0x7b, 0x7e, 0x26, 0x95, 0x30, 0xb9,
	0xa9, 0x8a, 0xec, 0x33, 0x84, 0x73, 0x07, 0xd1, 0x1c, 0x82, 0x33, 0x61, 0x79, 0xe2, 0x8d, 0xbd,
	0xc9, 0x68, 0x9a, 0xe6, 0x7f, 0x11, 0xf3, 0x37, 0xc2, 0x72, 0x64, 0x32, 0xe4, 0xd1, 0x07, 0x10,
	0x16, 0x9f, 0xb8, 0x54, 0x89, 0x8f, 0x05, 0xb7, 0x06, 0x05, 0x2f, 0x5c, 0xb6, 0xa9, 0x68, 0x98,
	0xd9, 0x4f, 0x0f, 0xa0, 0x47, 0xe9, 0x18, 0x46, 0x25, 0x5f, 0xdb, 0x77, 0xd5, 0x92, 0x5b, 0xb1,
	0x44, 0x61, 0xc2, 0x76, 0x21, 0xfa, 0x14, 0xc2, 0x4a, 0x7f, 0x13, 0x26, 0xf1, 0xc7, 0x64, 0x32,
	0x9a, 0xde, 0xfd, 0x8f, 0x46, 0xbe, 0x70, 0xc4, 0x97, 0xca, 0x9a, 0x0d, 0x6b, 0x8a, 0xd2, 0x05,
	0x40, 0x0f, 0xd2, 0xeb, 0x40, 0xbe, 0x88, 0x0d, 0xaa, 0xc4, 0xcc, 0x7d, 0xd2, 0xfb, 0x10, 0x9e,
	0xf3, 0xb2, 0x16, 0xed, 0x04, 0x87, 0x83, 0xee, 0x58, 0xcd, 0x1a, 0xd2, 0x13, 0x7f, 0xe6, 0x65,
	0x8f, 0x21, 0x44, 0x8c, 0xde, 0xe8, 0x1e, 0xe6, 0xda, 0x05, 0xad, 0x20, 0x4d, 0x21, 0x32, 0xa2,
	0xe4, 0x56, 0x9e, 0x37, 0x3d, 0x7d, 0xb6, 0x8d, 0xb3, 0x5f, 0x1e, 0xc4, 0x5b, 0x0b, 0xe9, 0x21,
	0x1c, 0x68, 0x55, 0x4a, 0x25, 0xb0, 0xc1, 0x55, 0xd6, 0x46, 0x34, 0x81, 0xcb, 0x7a, 0xb5, 0xc2,
	0x84, 0x8f, 0x89, 0x2e, 0xa4, 0x33, 0x08, 0xa4, 0x5a, 0xe9, 0x84, 0xa0, 0x13, 0x77, 0xfe, 0xbd,
	0x9e, 0x7c, 0xae, 0x56, 0xba, 0xf1, 0x01, 0x2b, 0xd2, 0xb7, 0x10, 0x6f, 0xa1, 0x3d, 0x2e, 0xdc,
	0xfb, 0xd3, 0x85, 0x9b, 0x7b, 0x3b, 0xef, 0x9a, 0xf0, 0xc3, 0x83, 0xc0, 0x61, 0x17, 0xd8, 0xdf,
	0x6d, 0x88, 0xeb, 0xb5, 0x30, 0xc7, 0xa7, 0x42, 0x59, 0xec, 0x1f, 0xb3, 0x1e, 0xa0, 0x8f, 0x20,
	0x2a, 0x75, 0xc1, 0xad, 0xd4, 0x2a, 0x21, 0x28, 0x7e, 0x34, 0x10, 0x7f, 0xdd, 0x12, 0xd8, 0x96,
	0xba, 0xe3, 0x5d, 0x30, 0xf6, 0x26, 0x51, 0xe7, 0x5d, 0xf6, 0x01, 0xa2, 0x8e, 0xed, 0x7c, 0x2c,
	0x74, 0xed, 0x26, 0x6e, 0x47, 0xed, 0x42, 0xf7, 0xa4, 0x52, 0xab, 0x53, 0x69, 0xeb, 0x65, 0xb7,
	0xa4, 0x1e, 0x70, 0x1b, 0x74, 0xfb, 0xc2, 0x24, 0x69, 0x36, 0xd8, 0xc5, 0xd9, 0x15, 0x80, 0x13,
	0x61, 0x99, 0xf8, 0x5a, 0x8b, 0xb5, 0xcd, 0x66, 0x10, 0x61, 0x54, 0x95, 0xf8, 0x23, 0xe1, 0xbb,
	0xdb, 0xdb, 0x19, 0xfe, 0x48, 0xed, 0x15, 0x20, 0x3c, 0x7d, 0x05, 0xe4, 0x78, 0x31, 0xa7, 0xcf,
	0x80, 0x9c, 0x08, 0x4b, 0x87, 0x77, 0xd3, 0x8b, 0xa4, 0x47, 0xfb, 0x93, 0x55, 0xb9, 0xc9, 0x2e,
	0x3d, 0x0f, 0xdf, 0x13, 0x53, 0x15, 0x1f, 0x0f, 0xf0, 0xb0, 0x1f, 0xfe, 0x0e, 0x00, 0x00, 0xff,
	0xff, 0x02, 0x4f, 0xb3, 0xb1, 0xe5, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// APIClient is the client API for API service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type APIClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetReply, error)
}

type aPIClient struct {
	cc *grpc.ClientConn
}

func NewAPIClient(cc *grpc.ClientConn) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetReply, error) {
	out := new(GetReply)
	err := c.cc.Invoke(ctx, "/index.miner.rpc.API/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APIServer is the server API for API service.
type APIServer interface {
	Get(context.Context, *GetRequest) (*GetReply, error)
}

// UnimplementedAPIServer can be embedded to have forward compatible implementations.
type UnimplementedAPIServer struct {
}

func (*UnimplementedAPIServer) Get(ctx context.Context, req *GetRequest) (*GetReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterAPIServer(s *grpc.Server, srv APIServer) {
	s.RegisterService(&_API_serviceDesc, srv)
}

func _API_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/index.miner.rpc.API/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _API_serviceDesc = grpc.ServiceDesc{
	ServiceName: "index.miner.rpc.API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _API_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
