{
 "title": "Textile Filecoin",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Lotus Height",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "textilefc_lotus_height_count", "legendFormat": " Height" }
   ]
  },
  {
   "title": "CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=\"docker_powergate_1\"}[1m]))",
     "legendFormat": "docker_powergate"
    }
   ]
  },
  {
   "title": "Mem RSS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "container_memory_rss{name=\"docker_powergate_1\"}"
    }
   ]
  },
  {
   "title": "Go routines",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "textilefc_process_cpu_goroutines{instance=\"powergate:8888\"}"
    }
   ]
  },
  {
   "title": "Network Output",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=\"docker_powergate_1\"}[1m] ) )",
     "legendFormat": "docker_powergate"
    }
   ]
  },
  {
   "title": "Network Input",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=\"docker_powergate_1\"}[1m]))",
     "legendFormat": "docker_powergate"
    }
   ]
  },
  {
   "title": "Heap Alloc",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "textilefc_process_heap_alloc{instance=\"powergate:8888\"}"
    }
   ]
  },
  { "title": "Miner index", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "On-Chain Refresh",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "textilefc_indexminer_onchain_refresh_progress"
    }
   ]
  },
  {
   "title": "Index Height",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "textilefc_index_miner_updated_height"
    }
   ]
  },
  {
   "title": "Full-Refresh Duration",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 10 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "textilefc_indexminer_refresh_duration{refreshtype=\"full\"}"
    }
   ]
  },
  {
   "title": "Delta-Refresh Duration",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 10 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "textilefc_indexminer_refresh_duration{refreshtype=\"delta\"}",
     "legendFormat": "delta-refresh-time"
    }
   ]
  },
  {
   "title": "Meta Refresh",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "textilefc_indexminer_meta_refresh_progress"
    }
   ]
  },
  {
   "title": "#Miners Ping Reply",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 10 },
   "targets": [
    {
     "expr": "textilefc_indexminer_meta_ping_count",
     "legendFormat": "{{ online }}"
    }
   ]
  },
  { "title": "Ask Index", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Full Refresh",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "textilefc_askindex_fullrefresh_progress"
    }
   ]
  },
  {
   "title": "Refresh Duration",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 15 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "textilefc_askindex_fullrefresh_duration"
    }
   ]
  },
  {
   "title": "Last Query-Ask Reply",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 15 },
   "targets": [
    {
     "expr": "textilefc_askindex_queryask_result",
     "legendFormat": "{{ askstatus }}"
    }
   ]
  },
  { "title": "Slashing Index", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Refresh",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "textilefc_indexslashing_refresh_progress"
    }
   ]
  },
  {
   "title": "Index Height",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 20 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "textilefc_indexslashing_updated_height"
    }
   ]
  }
 ]
}