// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.1
// source: proto/admin/v1/powergate_admin.proto

package v1

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	rpc "github.com/textileio/powergate/ffs/rpc"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CreateInstanceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateInstanceRequest) Reset() {
	*x = CreateInstanceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_admin_v1_powergate_admin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInstanceRequest) ProtoMessage() {}

func (x *CreateInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_powergate_admin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInstanceRequest.ProtoReflect.Descriptor instead.
func (*CreateInstanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_powergate_admin_proto_rawDescGZIP(), []int{0}
}

type CreateInstanceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Token string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *CreateInstanceResponse) Reset() {
	*x = CreateInstanceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_admin_v1_powergate_admin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInstanceResponse) ProtoMessage() {}

func (x *CreateInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_powergate_admin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInstanceResponse.ProtoReflect.Descriptor instead.
func (*CreateInstanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_powergate_admin_proto_rawDescGZIP(), []int{1}
}

func (x *CreateInstanceResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateInstanceResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ListInstancesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListInstancesRequest) Reset() {
	*x = ListInstancesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_admin_v1_powergate_admin_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListInstancesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInstancesRequest) ProtoMessage() {}

func (x *ListInstancesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_powergate_admin_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInstancesRequest.ProtoReflect.Descriptor instead.
func (*ListInstancesRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_powergate_admin_proto_rawDescGZIP(), []int{2}
}

type ListInstancesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Instances []string `protobuf:"bytes,1,rep,name=instances,proto3" json:"instances,omitempty"`
}

func (x *ListInstancesResponse) Reset() {
	*x = ListInstancesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_admin_v1_powergate_admin_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListInstancesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInstancesResponse) ProtoMessage() {}

func (x *ListInstancesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_powergate_admin_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInstancesResponse.ProtoReflect.Descriptor instead.
func (*ListInstancesResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_powergate_admin_proto_rawDescGZIP(), []int{3}
}

func (x *ListInstancesResponse) GetInstances() []string {
	if x != nil {
		return x.Instances
	}
	return nil
}

type GetQueuedStorageJobsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InstanceId string   `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Cids       []string `protobuf:"bytes,2,rep,name=cids,proto3" json:"cids,omitempty"`
}

func (x *GetQueuedStorageJobsRequest) Reset() {
	*x = GetQueuedStorageJobsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_admin_v1_powergate_admin_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetQueuedStorageJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueuedStorageJobsRequest) ProtoMessage() {}

func (x *GetQueuedStorageJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_powergate_admin_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueuedStorageJobsRequest.ProtoReflect.Descriptor instead.
func (*GetQueuedStorageJobsRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_powergate_admin_proto_rawDescGZIP(), []int{4}
}

func (x *GetQueuedStorageJobsRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *GetQueuedStorageJobsRequest) GetCids() []string {
	if x != nil {
		return x.Cids
	}
	return nil
}

type GetQueuedStorageJobsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StorageJobs []*rpc.Job `protobuf:"bytes,1,rep,name=storage_jobs,json=storageJobs,proto3" json:"storage_jobs,omitempty"`
}

func (x *GetQueuedStorageJobsResponse) Reset() {
	*x = GetQueuedStorageJobsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_admin_v1_powergate_admin_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetQueuedStorageJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueuedStorageJobsResponse) ProtoMessage() {}

func (x *GetQueuedStorageJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_powergate_admin_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueuedStorageJobsResponse.ProtoReflect.Descriptor instead.
func (*GetQueuedStorageJobsResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_powergate_admin_proto_rawDescGZIP(), []int{5}
}

func (x *GetQueuedStorageJobsResponse) GetStorageJobs() []*rpc.Job {
	if x != nil {
		return x.StorageJobs
	}
	return nil
}

type GetExecutingStorageJobsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InstanceId string   `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Cids       []string `protobuf:"bytes,2,rep,name=cids,proto3" json:"cids,omitempty"`
}

func (x *GetExecutingStorageJobsRequest) Reset() {
	*x = GetExecutingStorageJobsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_admin_v1_powergate_admin_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetExecutingStorageJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutingStorageJobsRequest) ProtoMessage() {}

func (x *GetExecutingStorageJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_powergate_admin_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutingStorageJobsRequest.ProtoReflect.Descriptor instead.
func (*GetExecutingStorageJobsRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_powergate_admin_proto_rawDescGZIP(), []int{6}
}

func (x *GetExecutingStorageJobsRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *GetExecutingStorageJobsRequest) GetCids() []string {
	if x != nil {
		return x.Cids
	}
	return nil
}

type GetExecutingStorageJobsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StorageJobs []*rpc.Job `protobuf:"bytes,1,rep,name=storage_jobs,json=storageJobs,proto3" json:"storage_jobs,omitempty"`
}

func (x *GetExecutingStorageJobsResponse) Reset() {
	*x = GetExecutingStorageJobsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_admin_v1_powergate_admin_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetExecutingStorageJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutingStorageJobsResponse) ProtoMessage() {}

func (x *GetExecutingStorageJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_powergate_admin_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutingStorageJobsResponse.ProtoReflect.Descriptor instead.
func (*GetExecutingStorageJobsResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_powergate_admin_proto_rawDescGZIP(), []int{7}
}

func (x *GetExecutingStorageJobsResponse) GetStorageJobs() []*rpc.Job {
	if x != nil {
		return x.StorageJobs
	}
	return nil
}

type GetLatestFinalStorageJobsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InstanceId string   `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Cids       []string `protobuf:"bytes,2,rep,name=cids,proto3" json:"cids,omitempty"`
}

func (x *GetLatestFinalStorageJobsRequest) Reset() {
	*x = GetLatestFinalStorageJobsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_admin_v1_powergate_admin_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLatestFinalStorageJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestFinalStorageJobsRequest) ProtoMessage() {}

func (x *GetLatestFinalStorageJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_powergate_admin_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestFinalStorageJobsRequest.ProtoReflect.Descriptor instead.
func (*GetLatestFinalStorageJobsRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_powergate_admin_proto_rawDescGZIP(), []int{8}
}

func (x *GetLatestFinalStorageJobsRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *GetLatestFinalStorageJobsRequest) GetCids() []string {
	if x != nil {
		return x.Cids
	}
	return nil
}

type GetLatestFinalStorageJobsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StorageJobs []*rpc.Job `protobuf:"bytes,1,rep,name=storage_jobs,json=storageJobs,proto3" json:"storage_jobs,omitempty"`
}

func (x *GetLatestFinalStorageJobsResponse) Reset() {
	*x = GetLatestFinalStorageJobsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_admin_v1_powergate_admin_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLatestFinalStorageJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestFinalStorageJobsResponse) ProtoMessage() {}

func (x *GetLatestFinalStorageJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_powergate_admin_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestFinalStorageJobsResponse.ProtoReflect.Descriptor instead.
func (*GetLatestFinalStorageJobsResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_powergate_admin_proto_rawDescGZIP(), []int{9}
}

func (x *GetLatestFinalStorageJobsResponse) GetStorageJobs() []*rpc.Job {
	if x != nil {
		return x.StorageJobs
	}
	return nil
}

type GetLatestSuccessfulStorageJobsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InstanceId string   `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Cids       []string `protobuf:"bytes,2,rep,name=cids,proto3" json:"cids,omitempty"`
}

func (x *GetLatestSuccessfulStorageJobsRequest) Reset() {
	*x = GetLatestSuccessfulStorageJobsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_admin_v1_powergate_admin_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLatestSuccessfulStorageJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestSuccessfulStorageJobsRequest) ProtoMessage() {}

func (x *GetLatestSuccessfulStorageJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_powergate_admin_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestSuccessfulStorageJobsRequest.ProtoReflect.Descriptor instead.
func (*GetLatestSuccessfulStorageJobsRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_powergate_admin_proto_rawDescGZIP(), []int{10}
}

func (x *GetLatestSuccessfulStorageJobsRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *GetLatestSuccessfulStorageJobsRequest) GetCids() []string {
	if x != nil {
		return x.Cids
	}
	return nil
}

type GetLatestSuccessfulStorageJobsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StorageJobs []*rpc.Job `protobuf:"bytes,1,rep,name=storage_jobs,json=storageJobs,proto3" json:"storage_jobs,omitempty"`
}

func (x *GetLatestSuccessfulStorageJobsResponse) Reset() {
	*x = GetLatestSuccessfulStorageJobsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_admin_v1_powergate_admin_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLatestSuccessfulStorageJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestSuccessfulStorageJobsResponse) ProtoMessage() {}

func (x *GetLatestSuccessfulStorageJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_powergate_admin_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestSuccessfulStorageJobsResponse.ProtoReflect.Descriptor instead.
func (*GetLatestSuccessfulStorageJobsResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_powergate_admin_proto_rawDescGZIP(), []int{11}
}

func (x *GetLatestSuccessfulStorageJobsResponse) GetStorageJobs() []*rpc.Job {
	if x != nil {
		return x.StorageJobs
	}
	return nil
}

var File_proto_admin_v1_powergate_admin_proto protoreflect.FileDescriptor

var file_proto_admin_v1_powergate_admin_proto_rawDesc = []byte{
	0x0a, 0x24, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x76, 0x31,
	0x2f, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x67, 0x61, 0x74, 0x65, 0x5f, 0x61, 0x64, 0x6d, 0x69, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x64,
	0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x1a, 0x11, 0x66, 0x66, 0x73, 0x2f, 0x72, 0x70, 0x63, 0x2f,
	0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x17, 0x0a, 0x15, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x3e, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x22, 0x16, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x35, 0x0a, 0x15, 0x4c, 0x69,
	0x73, 0x74, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x73, 0x22, 0x52, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x51, 0x75, 0x65, 0x75, 0x65, 0x64, 0x53, 0x74,
	0x6f, 0x72, 0x61, 0x67, 0x65, 0x4a, 0x6f, 0x62, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x04, 0x63, 0x69, 0x64, 0x73, 0x22, 0x4f, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x51, 0x75, 0x65, 0x75,
	0x65, 0x64, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x4a, 0x6f, 0x62, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x0c, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x5f, 0x6a, 0x6f, 0x62, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x66, 0x66,
	0x73, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x4a, 0x6f, 0x62, 0x52, 0x0b, 0x73, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x4a, 0x6f, 0x62, 0x73, 0x22, 0x55, 0x0a, 0x1e, 0x47, 0x65, 0x74, 0x45, 0x78, 0x65,
	0x63, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x4a, 0x6f, 0x62,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69,
	0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x64,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x64, 0x73, 0x22, 0x52, 0x0a,
	0x1f, 0x47, 0x65, 0x74, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x4a, 0x6f, 0x62, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2f, 0x0a, 0x0c, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x6a, 0x6f, 0x62, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x66, 0x66, 0x73, 0x2e, 0x72, 0x70, 0x63,
	0x2e, 0x4a, 0x6f, 0x62, 0x52, 0x0b, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x4a, 0x6f, 0x62,
	0x73, 0x22, 0x57, 0x0a, 0x20, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x46, 0x69,
	0x6e, 0x61, 0x6c, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x4a, 0x6f, 0x62, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x64, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x64, 0x73, 0x22, 0x54, 0x0a, 0x21, 0x47, 0x65,
	0x74, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x53, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x4a, 0x6f, 0x62, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2f, 0x0a, 0x0c, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x6a, 0x6f, 0x62, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x66, 0x66, 0x73, 0x2e, 0x72, 0x70, 0x63, 0x2e,
	0x4a, 0x6f, 0x62, 0x52, 0x0b, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x4a, 0x6f, 0x62, 0x73,
	0x22, 0x5c, 0x0a, 0x25, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x53, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x66, 0x75, 0x6c, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x4a, 0x6f,
	0x62, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69,
	0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x64, 0x73, 0x22, 0x59,
	0x0a, 0x26, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x53, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x66, 0x75, 0x6c, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x4a, 0x6f, 0x62, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x0c, 0x73, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x5f, 0x6a, 0x6f, 0x62, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x66, 0x66, 0x73, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x4a, 0x6f, 0x62, 0x52, 0x0b, 0x73, 0x74,
	0x6f, 0x72, 0x61, 0x67, 0x65, 0x4a, 0x6f, 0x62, 0x73, 0x32, 0xe6, 0x05, 0x0a, 0x15, 0x50, 0x6f,
	0x77, 0x65, 0x72, 0x67, 0x61, 0x74, 0x65, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x61, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x25, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x64,
	0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5e, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x12, 0x24, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x73, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x51, 0x75, 0x65,
	0x75, 0x65, 0x64, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x4a, 0x6f, 0x62, 0x73, 0x12, 0x2b,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x51, 0x75, 0x65, 0x75, 0x65, 0x64, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x4a, 0x6f, 0x62, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74,
	0x51, 0x75, 0x65, 0x75, 0x65, 0x64, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x4a, 0x6f, 0x62,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x7c, 0x0a, 0x17, 0x47,
	0x65, 0x74, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x4a, 0x6f, 0x62, 0x73, 0x12, 0x2e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61,
	0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x78, 0x65, 0x63, 0x75,
	0x74, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x4a, 0x6f, 0x62, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61,
	0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x78, 0x65, 0x63, 0x75,
	0x74, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x4a, 0x6f, 0x62, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x82, 0x01, 0x0a, 0x19, 0x47, 0x65,
	0x74, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x53, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x4a, 0x6f, 0x62, 0x73, 0x12, 0x30, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x74, 0x65,
	0x73, 0x74, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x4a, 0x6f,
	0x62, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x61,
	0x74, 0x65, 0x73, 0x74, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x4a, 0x6f, 0x62, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x91,
	0x01, 0x0a, 0x1e, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x53, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x66, 0x75, 0x6c, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x4a, 0x6f, 0x62,
	0x73, 0x12, 0x35, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x53, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x66, 0x75, 0x6c, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x4a, 0x6f, 0x62,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x36, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x74,
	0x65, 0x73, 0x74, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x66, 0x75, 0x6c, 0x53, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x4a, 0x6f, 0x62, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x74, 0x65, 0x78, 0x74, 0x69, 0x6c, 0x65, 0x69, 0x6f, 0x2f, 0x70, 0x6f, 0x77, 0x65, 0x72,
	0x67, 0x61, 0x74, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e,
	0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_admin_v1_powergate_admin_proto_rawDescOnce sync.Once
	file_proto_admin_v1_powergate_admin_proto_rawDescData = file_proto_admin_v1_powergate_admin_proto_rawDesc
)

func file_proto_admin_v1_powergate_admin_proto_rawDescGZIP() []byte {
	file_proto_admin_v1_powergate_admin_proto_rawDescOnce.Do(func() {
		file_proto_admin_v1_powergate_admin_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_admin_v1_powergate_admin_proto_rawDescData)
	})
	return file_proto_admin_v1_powergate_admin_proto_rawDescData
}

var file_proto_admin_v1_powergate_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_admin_v1_powergate_admin_proto_goTypes = []interface{}{
	(*CreateInstanceRequest)(nil),                  // 0: proto.admin.v1.CreateInstanceRequest
	(*CreateInstanceResponse)(nil),                 // 1: proto.admin.v1.CreateInstanceResponse
	(*ListInstancesRequest)(nil),                   // 2: proto.admin.v1.ListInstancesRequest
	(*ListInstancesResponse)(nil),                  // 3: proto.admin.v1.ListInstancesResponse
	(*GetQueuedStorageJobsRequest)(nil),            // 4: proto.admin.v1.GetQueuedStorageJobsRequest
	(*GetQueuedStorageJobsResponse)(nil),           // 5: proto.admin.v1.GetQueuedStorageJobsResponse
	(*GetExecutingStorageJobsRequest)(nil),         // 6: proto.admin.v1.GetExecutingStorageJobsRequest
	(*GetExecutingStorageJobsResponse)(nil),        // 7: proto.admin.v1.GetExecutingStorageJobsResponse
	(*GetLatestFinalStorageJobsRequest)(nil),       // 8: proto.admin.v1.GetLatestFinalStorageJobsRequest
	(*GetLatestFinalStorageJobsResponse)(nil),      // 9: proto.admin.v1.GetLatestFinalStorageJobsResponse
	(*GetLatestSuccessfulStorageJobsRequest)(nil),  // 10: proto.admin.v1.GetLatestSuccessfulStorageJobsRequest
	(*GetLatestSuccessfulStorageJobsResponse)(nil), // 11: proto.admin.v1.GetLatestSuccessfulStorageJobsResponse
	(*rpc.Job)(nil),                                // 12: ffs.rpc.Job
}
var file_proto_admin_v1_powergate_admin_proto_depIdxs = []int32{
	12, // 0: proto.admin.v1.GetQueuedStorageJobsResponse.storage_jobs:type_name -> ffs.rpc.Job
	12, // 1: proto.admin.v1.GetExecutingStorageJobsResponse.storage_jobs:type_name -> ffs.rpc.Job
	12, // 2: proto.admin.v1.GetLatestFinalStorageJobsResponse.storage_jobs:type_name -> ffs.rpc.Job
	12, // 3: proto.admin.v1.GetLatestSuccessfulStorageJobsResponse.storage_jobs:type_name -> ffs.rpc.Job
	0,  // 4: proto.admin.v1.PowergateAdminService.CreateInstance:input_type -> proto.admin.v1.CreateInstanceRequest
	2,  // 5: proto.admin.v1.PowergateAdminService.ListInstances:input_type -> proto.admin.v1.ListInstancesRequest
	4,  // 6: proto.admin.v1.PowergateAdminService.GetQueuedStorageJobs:input_type -> proto.admin.v1.GetQueuedStorageJobsRequest
	6,  // 7: proto.admin.v1.PowergateAdminService.GetExecutingStorageJobs:input_type -> proto.admin.v1.GetExecutingStorageJobsRequest
	8,  // 8: proto.admin.v1.PowergateAdminService.GetLatestFinalStorageJobs:input_type -> proto.admin.v1.GetLatestFinalStorageJobsRequest
	10, // 9: proto.admin.v1.PowergateAdminService.GetLatestSuccessfulStorageJobs:input_type -> proto.admin.v1.GetLatestSuccessfulStorageJobsRequest
	1,  // 10: proto.admin.v1.PowergateAdminService.CreateInstance:output_type -> proto.admin.v1.CreateInstanceResponse
	3,  // 11: proto.admin.v1.PowergateAdminService.ListInstances:output_type -> proto.admin.v1.ListInstancesResponse
	5,  // 12: proto.admin.v1.PowergateAdminService.GetQueuedStorageJobs:output_type -> proto.admin.v1.GetQueuedStorageJobsResponse
	7,  // 13: proto.admin.v1.PowergateAdminService.GetExecutingStorageJobs:output_type -> proto.admin.v1.GetExecutingStorageJobsResponse
	9,  // 14: proto.admin.v1.PowergateAdminService.GetLatestFinalStorageJobs:output_type -> proto.admin.v1.GetLatestFinalStorageJobsResponse
	11, // 15: proto.admin.v1.PowergateAdminService.GetLatestSuccessfulStorageJobs:output_type -> proto.admin.v1.GetLatestSuccessfulStorageJobsResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_admin_v1_powergate_admin_proto_init() }
func file_proto_admin_v1_powergate_admin_proto_init() {
	if File_proto_admin_v1_powergate_admin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_admin_v1_powergate_admin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateInstanceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_admin_v1_powergate_admin_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateInstanceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_admin_v1_powergate_admin_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListInstancesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_admin_v1_powergate_admin_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListInstancesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_admin_v1_powergate_admin_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetQueuedStorageJobsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_admin_v1_powergate_admin_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetQueuedStorageJobsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_admin_v1_powergate_admin_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetExecutingStorageJobsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_admin_v1_powergate_admin_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetExecutingStorageJobsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_admin_v1_powergate_admin_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLatestFinalStorageJobsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_admin_v1_powergate_admin_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLatestFinalStorageJobsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_admin_v1_powergate_admin_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLatestSuccessfulStorageJobsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_admin_v1_powergate_admin_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLatestSuccessfulStorageJobsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_admin_v1_powergate_admin_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_admin_v1_powergate_admin_proto_goTypes,
		DependencyIndexes: file_proto_admin_v1_powergate_admin_proto_depIdxs,
		MessageInfos:      file_proto_admin_v1_powergate_admin_proto_msgTypes,
	}.Build()
	File_proto_admin_v1_powergate_admin_proto = out.File
	file_proto_admin_v1_powergate_admin_proto_rawDesc = nil
	file_proto_admin_v1_powergate_admin_proto_goTypes = nil
	file_proto_admin_v1_powergate_admin_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PowergateAdminServiceClient is the client API for PowergateAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PowergateAdminServiceClient interface {
	CreateInstance(ctx context.Context, in *CreateInstanceRequest, opts ...grpc.CallOption) (*CreateInstanceResponse, error)
	ListInstances(ctx context.Context, in *ListInstancesRequest, opts ...grpc.CallOption) (*ListInstancesResponse, error)
	GetQueuedStorageJobs(ctx context.Context, in *GetQueuedStorageJobsRequest, opts ...grpc.CallOption) (*GetQueuedStorageJobsResponse, error)
	GetExecutingStorageJobs(ctx context.Context, in *GetExecutingStorageJobsRequest, opts ...grpc.CallOption) (*GetExecutingStorageJobsResponse, error)
	GetLatestFinalStorageJobs(ctx context.Context, in *GetLatestFinalStorageJobsRequest, opts ...grpc.CallOption) (*GetLatestFinalStorageJobsResponse, error)
	GetLatestSuccessfulStorageJobs(ctx context.Context, in *GetLatestSuccessfulStorageJobsRequest, opts ...grpc.CallOption) (*GetLatestSuccessfulStorageJobsResponse, error)
}

type powergateAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPowergateAdminServiceClient(cc grpc.ClientConnInterface) PowergateAdminServiceClient {
	return &powergateAdminServiceClient{cc}
}

func (c *powergateAdminServiceClient) CreateInstance(ctx context.Context, in *CreateInstanceRequest, opts ...grpc.CallOption) (*CreateInstanceResponse, error) {
	out := new(CreateInstanceResponse)
	err := c.cc.Invoke(ctx, "/proto.admin.v1.PowergateAdminService/CreateInstance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *powergateAdminServiceClient) ListInstances(ctx context.Context, in *ListInstancesRequest, opts ...grpc.CallOption) (*ListInstancesResponse, error) {
	out := new(ListInstancesResponse)
	err := c.cc.Invoke(ctx, "/proto.admin.v1.PowergateAdminService/ListInstances", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *powergateAdminServiceClient) GetQueuedStorageJobs(ctx context.Context, in *GetQueuedStorageJobsRequest, opts ...grpc.CallOption) (*GetQueuedStorageJobsResponse, error) {
	out := new(GetQueuedStorageJobsResponse)
	err := c.cc.Invoke(ctx, "/proto.admin.v1.PowergateAdminService/GetQueuedStorageJobs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *powergateAdminServiceClient) GetExecutingStorageJobs(ctx context.Context, in *GetExecutingStorageJobsRequest, opts ...grpc.CallOption) (*GetExecutingStorageJobsResponse, error) {
	out := new(GetExecutingStorageJobsResponse)
	err := c.cc.Invoke(ctx, "/proto.admin.v1.PowergateAdminService/GetExecutingStorageJobs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *powergateAdminServiceClient) GetLatestFinalStorageJobs(ctx context.Context, in *GetLatestFinalStorageJobsRequest, opts ...grpc.CallOption) (*GetLatestFinalStorageJobsResponse, error) {
	out := new(GetLatestFinalStorageJobsResponse)
	err := c.cc.Invoke(ctx, "/proto.admin.v1.PowergateAdminService/GetLatestFinalStorageJobs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *powergateAdminServiceClient) GetLatestSuccessfulStorageJobs(ctx context.Context, in *GetLatestSuccessfulStorageJobsRequest, opts ...grpc.CallOption) (*GetLatestSuccessfulStorageJobsResponse, error) {
	out := new(GetLatestSuccessfulStorageJobsResponse)
	err := c.cc.Invoke(ctx, "/proto.admin.v1.PowergateAdminService/GetLatestSuccessfulStorageJobs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PowergateAdminServiceServer is the server API for PowergateAdminService service.
type PowergateAdminServiceServer interface {
	CreateInstance(context.Context, *CreateInstanceRequest) (*CreateInstanceResponse, error)
	ListInstances(context.Context, *ListInstancesRequest) (*ListInstancesResponse, error)
	GetQueuedStorageJobs(context.Context, *GetQueuedStorageJobsRequest) (*GetQueuedStorageJobsResponse, error)
	GetExecutingStorageJobs(context.Context, *GetExecutingStorageJobsRequest) (*GetExecutingStorageJobsResponse, error)
	GetLatestFinalStorageJobs(context.Context, *GetLatestFinalStorageJobsRequest) (*GetLatestFinalStorageJobsResponse, error)
	GetLatestSuccessfulStorageJobs(context.Context, *GetLatestSuccessfulStorageJobsRequest) (*GetLatestSuccessfulStorageJobsResponse, error)
}

// UnimplementedPowergateAdminServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPowergateAdminServiceServer struct {
}

func (*UnimplementedPowergateAdminServiceServer) CreateInstance(context.Context, *CreateInstanceRequest) (*CreateInstanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateInstance not implemented")
}
func (*UnimplementedPowergateAdminServiceServer) ListInstances(context.Context, *ListInstancesRequest) (*ListInstancesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListInstances not implemented")
}
func (*UnimplementedPowergateAdminServiceServer) GetQueuedStorageJobs(context.Context, *GetQueuedStorageJobsRequest) (*GetQueuedStorageJobsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQueuedStorageJobs not implemented")
}
func (*UnimplementedPowergateAdminServiceServer) GetExecutingStorageJobs(context.Context, *GetExecutingStorageJobsRequest) (*GetExecutingStorageJobsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExecutingStorageJobs not implemented")
}
func (*UnimplementedPowergateAdminServiceServer) GetLatestFinalStorageJobs(context.Context, *GetLatestFinalStorageJobsRequest) (*GetLatestFinalStorageJobsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLatestFinalStorageJobs not implemented")
}
func (*UnimplementedPowergateAdminServiceServer) GetLatestSuccessfulStorageJobs(context.Context, *GetLatestSuccessfulStorageJobsRequest) (*GetLatestSuccessfulStorageJobsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLatestSuccessfulStorageJobs not implemented")
}

func RegisterPowergateAdminServiceServer(s *grpc.Server, srv PowergateAdminServiceServer) {
	s.RegisterService(&_PowergateAdminService_serviceDesc, srv)
}

func _PowergateAdminService_CreateInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PowergateAdminServiceServer).CreateInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.admin.v1.PowergateAdminService/CreateInstance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PowergateAdminServiceServer).CreateInstance(ctx, req.(*CreateInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PowergateAdminService_ListInstances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInstancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PowergateAdminServiceServer).ListInstances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.admin.v1.PowergateAdminService/ListInstances",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PowergateAdminServiceServer).ListInstances(ctx, req.(*ListInstancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PowergateAdminService_GetQueuedStorageJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQueuedStorageJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PowergateAdminServiceServer).GetQueuedStorageJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.admin.v1.PowergateAdminService/GetQueuedStorageJobs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PowergateAdminServiceServer).GetQueuedStorageJobs(ctx, req.(*GetQueuedStorageJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PowergateAdminService_GetExecutingStorageJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExecutingStorageJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PowergateAdminServiceServer).GetExecutingStorageJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.admin.v1.PowergateAdminService/GetExecutingStorageJobs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PowergateAdminServiceServer).GetExecutingStorageJobs(ctx, req.(*GetExecutingStorageJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PowergateAdminService_GetLatestFinalStorageJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestFinalStorageJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PowergateAdminServiceServer).GetLatestFinalStorageJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.admin.v1.PowergateAdminService/GetLatestFinalStorageJobs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PowergateAdminServiceServer).GetLatestFinalStorageJobs(ctx, req.(*GetLatestFinalStorageJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PowergateAdminService_GetLatestSuccessfulStorageJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestSuccessfulStorageJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PowergateAdminServiceServer).GetLatestSuccessfulStorageJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.admin.v1.PowergateAdminService/GetLatestSuccessfulStorageJobs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PowergateAdminServiceServer).GetLatestSuccessfulStorageJobs(ctx, req.(*GetLatestSuccessfulStorageJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PowergateAdminService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.admin.v1.PowergateAdminService",
	HandlerType: (*PowergateAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateInstance",
			Handler:    _PowergateAdminService_CreateInstance_Handler,
		},
		{
			MethodName: "ListInstances",
			Handler:    _PowergateAdminService_ListInstances_Handler,
		},
		{
			MethodName: "GetQueuedStorageJobs",
			Handler:    _PowergateAdminService_GetQueuedStorageJobs_Handler,
		},
		{
			MethodName: "GetExecutingStorageJobs",
			Handler:    _PowergateAdminService_GetExecutingStorageJobs_Handler,
		},
		{
			MethodName: "GetLatestFinalStorageJobs",
			Handler:    _PowergateAdminService_GetLatestFinalStorageJobs_Handler,
		},
		{
			MethodName: "GetLatestSuccessfulStorageJobs",
			Handler:    _PowergateAdminService_GetLatestSuccessfulStorageJobs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/admin/v1/powergate_admin.proto",
}
